//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.tariffservices.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for getTariffTableByTariffTypeTransactionTypeEffectiveDateAndBankId complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getTariffTableByTariffTypeTransactionTypeEffectiveDateAndBankId">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tariffType" type="{http://service.tariffservices.ewallet.esolutions.co.zw/}tariffType" minOccurs="0"/>
 *         &lt;element name="transactionType" type="{http://service.tariffservices.ewallet.esolutions.co.zw/}transactionType" minOccurs="0"/>
 *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="agentType" type="{http://service.tariffservices.ewallet.esolutions.co.zw/}agentType" minOccurs="0"/>
 *         &lt;element name="bankid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTariffTableByTariffTypeTransactionTypeEffectiveDateAndBankId", namespace = "http://service.tariffservices.ewallet.esolutions.co.zw/", propOrder = {
    "tariffType",
    "transactionType",
    "effectiveDate",
    "agentType",
    "bankid"
})
public class GetTariffTableByTariffTypeTransactionTypeEffectiveDateAndBankId {

    protected TariffType tariffType;
    protected TransactionType transactionType;
    protected XMLGregorianCalendar effectiveDate;
    protected AgentType agentType;
    protected String bankid;

    /**
     * Gets the value of the tariffType property.
     * 
     * @return
     *     possible object is
     *     {@link TariffType }
     *     
     */
    public TariffType getTariffType() {
        return tariffType;
    }

    /**
     * Sets the value of the tariffType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TariffType }
     *     
     */
    public void setTariffType(TariffType value) {
        this.tariffType = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionType }
     *     
     */
    public TransactionType getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionType }
     *     
     */
    public void setTransactionType(TransactionType value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the agentType property.
     * 
     * @return
     *     possible object is
     *     {@link AgentType }
     *     
     */
    public AgentType getAgentType() {
        return agentType;
    }

    /**
     * Sets the value of the agentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgentType }
     *     
     */
    public void setAgentType(AgentType value) {
        this.agentType = value;
    }

    /**
     * Gets the value of the bankid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankid() {
        return bankid;
    }

    /**
     * Sets the value of the bankid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankid(String value) {
        this.bankid = value;
    }

}
