package zw.co.esolutions.ewallet.enums;

public enum BankAccountType {
	E_WALLET,
	POOL_CONTROL,
	TARIFFS_CONTROL,
	PAYOUT_CONTROL,
	BANK_SUSPENSE,
	MERCHANT_SUSPENSE,
	SAVINGS,
	TOPUP_SUSPENSE_ACCOUNT,
	CURRENT,
	CHEQUE,
	BRANCH_CASH_ACCOUNT,
	EWALLET_BRANCH_CASH_ACCOUNT,
	EWALLET_BALANCING_SUSPENSE_ACCOUNT,
	MOBILE_TO_BANK_CONTROL,
	BANK_TO_MOBILE_CONTROL,
	BANK_TO_NON_MOBILE_CONTROL,
	SUSPENSE,
	//Account types used for agents
	AGENT_EWALLET, 
	AGENT_COMMISSION_SUSPENSE, 
	AGENT_COMMISSION_SOURCE,
	IB_EWALLET_SUSPENSE;
}
