package zw.co.esolutions.ewallet.enums;

public enum TransactionStatus {
	VEREQ,
	VERES,
	PAREQ, 
	BANK_REQUEST,
	DRAFT,
	BANK_RESPONSE,
	AWAITING_COLLECTION,
	CREDIT_REQUEST,
	COMPLETED, 
	FAILED, 
	AWAITING_APPROVAL,
	MANUAL_RESOLVE, 
	AWAITING_DEBIT_RES, 
	DISAPPROVED,
	AWAITING_COMPLETION_APPROVAL,
	AWAITING_FAILURE_APPROVAL,
	REVERSED,
	REVERSAL_REQUEST ,
	REVERSAL_RESPONSE,
	EXPIRED, 
	TIMEOUT, 
	CREDIT_RESPONSE, 
	ACCOUNT_VALIDATION_RQST;
	
}
