//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.zimswitch.airtimeportal;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the zw.co.zimswitch.airtimeportal package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AirtimeResponse_QNAME = new QName("http://www.zimswitch.co.zw/AirtimePortal", "AirtimeResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: zw.co.zimswitch.airtimeportal
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DirectTopupResponse }
     * 
     */
    public DirectTopupResponse createDirectTopupResponse() {
        return new DirectTopupResponse();
    }

    /**
     * Create an instance of {@link AirtimeResponse }
     * 
     */
    public AirtimeResponse createAirtimeResponse() {
        return new AirtimeResponse();
    }

    /**
     * Create an instance of {@link DirectTopup }
     * 
     */
    public DirectTopup createDirectTopup() {
        return new DirectTopup();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AirtimeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.zimswitch.co.zw/AirtimePortal", name = "AirtimeResponse")
    public JAXBElement<AirtimeResponse> createAirtimeResponse(AirtimeResponse value) {
        return new JAXBElement<AirtimeResponse>(_AirtimeResponse_QNAME, AirtimeResponse.class, null, value);
    }

}
