SELECT * FROM BANKIF.TARIFFTABLE WHERE TRANSACTIONTYPE LIKE '%TRANSFER%' AND EFFECTIVEDATE < '2011-06-22';

DELETE FROM BANKIF.TARIFF WHERE TARIFFTABLE_ID IN (SELECT id FROM BANKIF.TARIFFTABLE WHERE TRANSACTIONTYPE LIKE '%TRANSFER%' AND STATUS = 'INACTIVE');

DELETE FROM BANKIF.TARIFFTABLE WHERE TRANSACTIONTYPE LIKE '%TRANSFER%' AND STATUS = 'INACTIVE'

DELETE FROM BANKIF.TARIFF WHERE TARIFFTABLE_ID IN (SELECT ID FROM BANKIF.TARIFFTABLE WHERE TRANSACTIONTYPE LIKE 'EWALLET_TO_EWALLET_TRANSFER' AND STATUS = 'INACTIVE');
DELETE FROM BANKIF.TARIFFTABLE WHERE TRANSACTIONTYPE LIKE 'EWALLET_TO_EWALLET_TRANSFER' AND STATUS = 'INACTIVE'

DELETE FROM BANKIF.TARIFFTABLE WHERE TRANSACTIONTYPE LIKE '%TRANSFER%' AND EFFECTIVEDATE < '2011-06-22'



DELETE FROM BANKIF.TARIFF WHERE TARIFFTABLE_ID IN (SELECT ID FROM BANKIF.TARIFFTABLE WHERE TRANSACTIONTYPE LIKE '%DEPOSIT%');
DELETE FROM BANKIF.TARIFFTABLE WHERE TRANSACTIONTYPE LIKE '%DEPOSIT%'



DELETE FROM BANKIF.TARIFF WHERE TARIFFTABLE_ID IN (SELECT ID FROM BANKIF.TARIFFTABLE WHERE TRANSACTIONTYPE LIKE 'MINI%');
DELETE FROM BANKIF.TARIFFTABLE WHERE TRANSACTIONTYPE LIKE 'MINI%'