//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.limitservices.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "LimitService", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LimitService {


    /**
     * 
     * @param userName
     * @param limit
     * @return
     *     returns zw.co.esolutions.ewallet.limitservices.service.Limit
     * @throws EWalletException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createLimit", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.CreateLimit")
    @ResponseWrapper(localName = "createLimitResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.CreateLimitResponse")
    public Limit createLimit(
        @WebParam(name = "limit", targetNamespace = "")
        Limit limit,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws EWalletException_Exception
    ;

    /**
     * 
     * @param userName
     * @param limitId
     * @return
     *     returns java.lang.String
     * @throws EWalletException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteLimit", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.DeleteLimit")
    @ResponseWrapper(localName = "deleteLimitResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.DeleteLimitResponse")
    public String deleteLimit(
        @WebParam(name = "limitId", targetNamespace = "")
        String limitId,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws EWalletException_Exception
    ;

    /**
     * 
     * @param limitId
     * @return
     *     returns zw.co.esolutions.ewallet.limitservices.service.Limit
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findLimitById", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.FindLimitById")
    @ResponseWrapper(localName = "findLimitByIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.FindLimitByIdResponse")
    public Limit findLimitById(
        @WebParam(name = "limitId", targetNamespace = "")
        String limitId);

    /**
     * 
     * @param status
     * @param bankId
     * @param type
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.limitservices.service.Limit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLimitByTypeAndStatusAndBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByTypeAndStatusAndBankId")
    @ResponseWrapper(localName = "getLimitByTypeAndStatusAndBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByTypeAndStatusAndBankIdResponse")
    public List<Limit> getLimitByTypeAndStatusAndBankId(
        @WebParam(name = "type", targetNamespace = "")
        TransactionType type,
        @WebParam(name = "status", targetNamespace = "")
        LimitStatus status,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param status
     * @param bankId
     * @param valueType
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.limitservices.service.Limit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLimitByValueTypeAndStatusAndBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByValueTypeAndStatusAndBankId")
    @ResponseWrapper(localName = "getLimitByValueTypeAndStatusAndBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByValueTypeAndStatusAndBankIdResponse")
    public List<Limit> getLimitByValueTypeAndStatusAndBankId(
        @WebParam(name = "valueType", targetNamespace = "")
        LimitValueType valueType,
        @WebParam(name = "status", targetNamespace = "")
        LimitStatus status,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param status
     * @param bankId
     * @param type
     * @param periodtype
     * @param valueType
     * @param accountClass
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.limitservices.service.Limit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLimitByAccountClassTypeValueTypeStatusPeriodTypeAndBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByAccountClassTypeValueTypeStatusPeriodTypeAndBankId")
    @ResponseWrapper(localName = "getLimitByAccountClassTypeValueTypeStatusPeriodTypeAndBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByAccountClassTypeValueTypeStatusPeriodTypeAndBankIdResponse")
    public List<Limit> getLimitByAccountClassTypeValueTypeStatusPeriodTypeAndBankId(
        @WebParam(name = "accountClass", targetNamespace = "")
        BankAccountClass accountClass,
        @WebParam(name = "type", targetNamespace = "")
        TransactionType type,
        @WebParam(name = "valueType", targetNamespace = "")
        LimitValueType valueType,
        @WebParam(name = "status", targetNamespace = "")
        LimitStatus status,
        @WebParam(name = "periodtype", targetNamespace = "")
        LimitPeriodType periodtype,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param status
     * @param effectiveDate
     * @param bankId
     * @param valueType
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.limitservices.service.Limit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLimitByValueTypeEffectiveDateStatusAndBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByValueTypeEffectiveDateStatusAndBankId")
    @ResponseWrapper(localName = "getLimitByValueTypeEffectiveDateStatusAndBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByValueTypeEffectiveDateStatusAndBankIdResponse")
    public List<Limit> getLimitByValueTypeEffectiveDateStatusAndBankId(
        @WebParam(name = "valueType", targetNamespace = "")
        LimitValueType valueType,
        @WebParam(name = "effectiveDate", targetNamespace = "")
        XMLGregorianCalendar effectiveDate,
        @WebParam(name = "status", targetNamespace = "")
        LimitStatus status,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param status
     * @param effectiveDate
     * @param bankId
     * @param type
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.limitservices.service.Limit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLimitByTypeEffectiveDateStatusAndBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByTypeEffectiveDateStatusAndBankId")
    @ResponseWrapper(localName = "getLimitByTypeEffectiveDateStatusAndBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByTypeEffectiveDateStatusAndBankIdResponse")
    public List<Limit> getLimitByTypeEffectiveDateStatusAndBankId(
        @WebParam(name = "type", targetNamespace = "")
        TransactionType type,
        @WebParam(name = "effectiveDate", targetNamespace = "")
        XMLGregorianCalendar effectiveDate,
        @WebParam(name = "status", targetNamespace = "")
        LimitStatus status,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param status
     * @param effectiveDate
     * @param bankId
     * @param type
     * @param valueType
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.limitservices.service.Limit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLimitByTypeValueTypeEffectiveDateStatusAndBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByTypeValueTypeEffectiveDateStatusAndBankId")
    @ResponseWrapper(localName = "getLimitByTypeValueTypeEffectiveDateStatusAndBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByTypeValueTypeEffectiveDateStatusAndBankIdResponse")
    public List<Limit> getLimitByTypeValueTypeEffectiveDateStatusAndBankId(
        @WebParam(name = "type", targetNamespace = "")
        TransactionType type,
        @WebParam(name = "valueType", targetNamespace = "")
        LimitValueType valueType,
        @WebParam(name = "effectiveDate", targetNamespace = "")
        XMLGregorianCalendar effectiveDate,
        @WebParam(name = "status", targetNamespace = "")
        LimitStatus status,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param status
     * @param effectiveDate
     * @param bankId
     * @param endDate
     * @param type
     * @param valueType
     * @param accountClass
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.limitservices.service.Limit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLimitByAccountClassTypeValueTypeEffectiveDateEndDateStatusAndBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByAccountClassTypeValueTypeEffectiveDateEndDateStatusAndBankId")
    @ResponseWrapper(localName = "getLimitByAccountClassTypeValueTypeEffectiveDateEndDateStatusAndBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByAccountClassTypeValueTypeEffectiveDateEndDateStatusAndBankIdResponse")
    public List<Limit> getLimitByAccountClassTypeValueTypeEffectiveDateEndDateStatusAndBankId(
        @WebParam(name = "accountClass", targetNamespace = "")
        BankAccountClass accountClass,
        @WebParam(name = "type", targetNamespace = "")
        TransactionType type,
        @WebParam(name = "valueType", targetNamespace = "")
        LimitValueType valueType,
        @WebParam(name = "effectiveDate", targetNamespace = "")
        XMLGregorianCalendar effectiveDate,
        @WebParam(name = "endDate", targetNamespace = "")
        XMLGregorianCalendar endDate,
        @WebParam(name = "status", targetNamespace = "")
        LimitStatus status,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param effectiveDate
     * @param bankId
     * @param endDate
     * @param type
     * @param periodType
     * @param valueType
     * @param accountClass
     * @return
     *     returns zw.co.esolutions.ewallet.limitservices.service.Limit
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActiveLimitByAccountClassTypeValueTypeEffectiveDateEndDateStatusPeriodTypeAndBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetActiveLimitByAccountClassTypeValueTypeEffectiveDateEndDateStatusPeriodTypeAndBankId")
    @ResponseWrapper(localName = "getActiveLimitByAccountClassTypeValueTypeEffectiveDateEndDateStatusPeriodTypeAndBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetActiveLimitByAccountClassTypeValueTypeEffectiveDateEndDateStatusPeriodTypeAndBankIdResponse")
    public Limit getActiveLimitByAccountClassTypeValueTypeEffectiveDateEndDateStatusPeriodTypeAndBankId(
        @WebParam(name = "accountClass", targetNamespace = "")
        BankAccountClass accountClass,
        @WebParam(name = "type", targetNamespace = "")
        TransactionType type,
        @WebParam(name = "valueType", targetNamespace = "")
        LimitValueType valueType,
        @WebParam(name = "effectiveDate", targetNamespace = "")
        XMLGregorianCalendar effectiveDate,
        @WebParam(name = "endDate", targetNamespace = "")
        XMLGregorianCalendar endDate,
        @WebParam(name = "periodType", targetNamespace = "")
        LimitPeriodType periodType,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.limitservices.service.Limit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLimits", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetAllLimits")
    @ResponseWrapper(localName = "getAllLimitsResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetAllLimitsResponse")
    public List<Limit> getAllLimits();

    /**
     * 
     * @param bankId
     * @param type
     * @param periodType
     * @param accountClass
     * @param onDate
     * @return
     *     returns zw.co.esolutions.ewallet.limitservices.service.Limit
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValidLimitOnDateByBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetValidLimitOnDateByBankId")
    @ResponseWrapper(localName = "getValidLimitOnDateByBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetValidLimitOnDateByBankIdResponse")
    public Limit getValidLimitOnDateByBankId(
        @WebParam(name = "type", targetNamespace = "")
        TransactionType type,
        @WebParam(name = "accountClass", targetNamespace = "")
        BankAccountClass accountClass,
        @WebParam(name = "onDate", targetNamespace = "")
        XMLGregorianCalendar onDate,
        @WebParam(name = "periodType", targetNamespace = "")
        LimitPeriodType periodType,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param limitType
     * @param bankId
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.limitservices.service.Limit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLimitByTypeAndBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByTypeAndBankId")
    @ResponseWrapper(localName = "getLimitByTypeAndBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByTypeAndBankIdResponse")
    public List<Limit> getLimitByTypeAndBankId(
        @WebParam(name = "limitType", targetNamespace = "")
        TransactionType limitType,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param bankId
     * @param accountClass
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.limitservices.service.Limit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLimitByAccountClassAndBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByAccountClassAndBankId")
    @ResponseWrapper(localName = "getLimitByAccountClassAndBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByAccountClassAndBankIdResponse")
    public List<Limit> getLimitByAccountClassAndBankId(
        @WebParam(name = "accountClass", targetNamespace = "")
        BankAccountClass accountClass,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param bankId
     * @param limitDate
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.limitservices.service.Limit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEffectiveLimitsByBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetEffectiveLimitsByBankId")
    @ResponseWrapper(localName = "getEffectiveLimitsByBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetEffectiveLimitsByBankIdResponse")
    public List<Limit> getEffectiveLimitsByBankId(
        @WebParam(name = "limitDate", targetNamespace = "")
        XMLGregorianCalendar limitDate,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param bankId
     * @param valueType
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.limitservices.service.Limit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLimitByValueTypeAndBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByValueTypeAndBankId")
    @ResponseWrapper(localName = "getLimitByValueTypeAndBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByValueTypeAndBankIdResponse")
    public List<Limit> getLimitByValueTypeAndBankId(
        @WebParam(name = "valueType", targetNamespace = "")
        LimitValueType valueType,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param bankId
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.limitservices.service.Limit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLimitsByBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetAllLimitsByBankId")
    @ResponseWrapper(localName = "getAllLimitsByBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetAllLimitsByBankIdResponse")
    public List<Limit> getAllLimitsByBankId(
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param status
     * @param bankId
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.limitservices.service.Limit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLimitByStatusAndBankId", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByStatusAndBankId")
    @ResponseWrapper(localName = "getLimitByStatusAndBankIdResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.GetLimitByStatusAndBankIdResponse")
    public List<Limit> getLimitByStatusAndBankId(
        @WebParam(name = "status", targetNamespace = "")
        LimitStatus status,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param userName
     * @param limit
     * @return
     *     returns zw.co.esolutions.ewallet.limitservices.service.Limit
     * @throws EWalletException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editLimit", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.EditLimit")
    @ResponseWrapper(localName = "editLimitResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.EditLimitResponse")
    public Limit editLimit(
        @WebParam(name = "limit", targetNamespace = "")
        Limit limit,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws EWalletException_Exception
    ;

    /**
     * 
     * @param userName
     * @param limit
     * @return
     *     returns zw.co.esolutions.ewallet.limitservices.service.Limit
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "approveLimit", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.ApproveLimit")
    @ResponseWrapper(localName = "approveLimitResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.ApproveLimitResponse")
    public Limit approveLimit(
        @WebParam(name = "limit", targetNamespace = "")
        Limit limit,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param userName
     * @param limit
     * @return
     *     returns zw.co.esolutions.ewallet.limitservices.service.Limit
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "disapproveLimit", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.DisapproveLimit")
    @ResponseWrapper(localName = "disapproveLimitResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.DisapproveLimitResponse")
    public Limit disapproveLimit(
        @WebParam(name = "limit", targetNamespace = "")
        Limit limit,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param userName
     * @param limit
     * @return
     *     returns zw.co.esolutions.ewallet.limitservices.service.Limit
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "activateLimit", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.ActivateLimit")
    @ResponseWrapper(localName = "activateLimitResponse", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.limitservices.service.ActivateLimitResponse")
    public Limit activateLimit(
        @WebParam(name = "limit", targetNamespace = "")
        Limit limit,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

}
