//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package zw.co.esolutions.mcommerce.refgen.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ReferenceGeneratorService", targetNamespace = "http://service.refgen.mcommerce.esolutions.co.zw/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReferenceGeneratorService {


    /**
     * 
     * @param sequenceName
     * @param maxValue
     * @param year
     * @param minValue
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNextNumberInSequence", targetNamespace = "http://service.refgen.mcommerce.esolutions.co.zw/", className = "zw.co.esolutions.mcommerce.refgen.service.GetNextNumberInSequence")
    @ResponseWrapper(localName = "getNextNumberInSequenceResponse", targetNamespace = "http://service.refgen.mcommerce.esolutions.co.zw/", className = "zw.co.esolutions.mcommerce.refgen.service.GetNextNumberInSequenceResponse")
    public long getNextNumberInSequence(
        @WebParam(name = "sequenceName", targetNamespace = "")
        String sequenceName,
        @WebParam(name = "year", targetNamespace = "")
        String year,
        @WebParam(name = "minValue", targetNamespace = "")
        long minValue,
        @WebParam(name = "maxValue", targetNamespace = "")
        long maxValue);

    /**
     * 
     * @param prefix
     * @param sequenceName
     * @param maxValue
     * @param year
     * @param minValue
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateUUID", targetNamespace = "http://service.refgen.mcommerce.esolutions.co.zw/", className = "zw.co.esolutions.mcommerce.refgen.service.GenerateUUID")
    @ResponseWrapper(localName = "generateUUIDResponse", targetNamespace = "http://service.refgen.mcommerce.esolutions.co.zw/", className = "zw.co.esolutions.mcommerce.refgen.service.GenerateUUIDResponse")
    public String generateUUID(
        @WebParam(name = "sequenceName", targetNamespace = "")
        String sequenceName,
        @WebParam(name = "prefix", targetNamespace = "")
        String prefix,
        @WebParam(name = "year", targetNamespace = "")
        String year,
        @WebParam(name = "minValue", targetNamespace = "")
        long minValue,
        @WebParam(name = "maxValue", targetNamespace = "")
        long maxValue);

}
