//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.mobile.banking.services;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the zw.co.esolutions.mobile.banking.services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetBanksResponse_QNAME = new QName("http://services.banking.mobile.esolutions.co.zw/", "getBanksResponse");
    private final static QName _GetBanks_QNAME = new QName("http://services.banking.mobile.esolutions.co.zw/", "getBanks");
    private final static QName _SubmitTransactionResponse_QNAME = new QName("http://services.banking.mobile.esolutions.co.zw/", "submitTransactionResponse");
    private final static QName _GetMerchantsResponse_QNAME = new QName("http://services.banking.mobile.esolutions.co.zw/", "getMerchantsResponse");
    private final static QName _SubmitTransaction_QNAME = new QName("http://services.banking.mobile.esolutions.co.zw/", "submitTransaction");
    private final static QName _GetMerchants_QNAME = new QName("http://services.banking.mobile.esolutions.co.zw/", "getMerchants");
    private final static QName _VerifyPasswordResponse_QNAME = new QName("http://services.banking.mobile.esolutions.co.zw/", "verifyPasswordResponse");
    private final static QName _VerifyPassword_QNAME = new QName("http://services.banking.mobile.esolutions.co.zw/", "verifyPassword");
    private final static QName _VerifyEnrolment_QNAME = new QName("http://services.banking.mobile.esolutions.co.zw/", "verifyEnrolment");
    private final static QName _VerifyEnrolmentResponse_QNAME = new QName("http://services.banking.mobile.esolutions.co.zw/", "verifyEnrolmentResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: zw.co.esolutions.mobile.banking.services
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubmitTransactionResponse }
     * 
     */
    public SubmitTransactionResponse createSubmitTransactionResponse() {
        return new SubmitTransactionResponse();
    }

    /**
     * Create an instance of {@link TransactionResponse }
     * 
     */
    public TransactionResponse createTransactionResponse() {
        return new TransactionResponse();
    }

    /**
     * Create an instance of {@link GetMerchantsResponse }
     * 
     */
    public GetMerchantsResponse createGetMerchantsResponse() {
        return new GetMerchantsResponse();
    }

    /**
     * Create an instance of {@link VerifyEnrolmentResponse }
     * 
     */
    public VerifyEnrolmentResponse createVerifyEnrolmentResponse() {
        return new VerifyEnrolmentResponse();
    }

    /**
     * Create an instance of {@link GetMerchants }
     * 
     */
    public GetMerchants createGetMerchants() {
        return new GetMerchants();
    }

    /**
     * Create an instance of {@link GetBanksResponse }
     * 
     */
    public GetBanksResponse createGetBanksResponse() {
        return new GetBanksResponse();
    }

    /**
     * Create an instance of {@link SubmitTransaction }
     * 
     */
    public SubmitTransaction createSubmitTransaction() {
        return new SubmitTransaction();
    }

    /**
     * Create an instance of {@link MerchantInfo }
     * 
     */
    public MerchantInfo createMerchantInfo() {
        return new MerchantInfo();
    }

    /**
     * Create an instance of {@link BankResponse }
     * 
     */
    public BankResponse createBankResponse() {
        return new BankResponse();
    }

    /**
     * Create an instance of {@link MerchantRequest }
     * 
     */
    public MerchantRequest createMerchantRequest() {
        return new MerchantRequest();
    }

    /**
     * Create an instance of {@link GetBanks }
     * 
     */
    public GetBanks createGetBanks() {
        return new GetBanks();
    }

    /**
     * Create an instance of {@link VerifyEnrolment }
     * 
     */
    public VerifyEnrolment createVerifyEnrolment() {
        return new VerifyEnrolment();
    }

    /**
     * Create an instance of {@link TransactionRequest }
     * 
     */
    public TransactionRequest createTransactionRequest() {
        return new TransactionRequest();
    }

    /**
     * Create an instance of {@link VerifyPasswordResponse }
     * 
     */
    public VerifyPasswordResponse createVerifyPasswordResponse() {
        return new VerifyPasswordResponse();
    }

    /**
     * Create an instance of {@link MerchantResponse }
     * 
     */
    public MerchantResponse createMerchantResponse() {
        return new MerchantResponse();
    }

    /**
     * Create an instance of {@link Pareq }
     * 
     */
    public Pareq createPareq() {
        return new Pareq();
    }

    /**
     * Create an instance of {@link VerifyPassword }
     * 
     */
    public VerifyPassword createVerifyPassword() {
        return new VerifyPassword();
    }

    /**
     * Create an instance of {@link Vereq }
     * 
     */
    public Vereq createVereq() {
        return new Vereq();
    }

    /**
     * Create an instance of {@link Pares }
     * 
     */
    public Pares createPares() {
        return new Pares();
    }

    /**
     * Create an instance of {@link BankRequest }
     * 
     */
    public BankRequest createBankRequest() {
        return new BankRequest();
    }

    /**
     * Create an instance of {@link Veres }
     * 
     */
    public Veres createVeres() {
        return new Veres();
    }

    /**
     * Create an instance of {@link BankInfo }
     * 
     */
    public BankInfo createBankInfo() {
        return new BankInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBanksResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.banking.mobile.esolutions.co.zw/", name = "getBanksResponse")
    public JAXBElement<GetBanksResponse> createGetBanksResponse(GetBanksResponse value) {
        return new JAXBElement<GetBanksResponse>(_GetBanksResponse_QNAME, GetBanksResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBanks }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.banking.mobile.esolutions.co.zw/", name = "getBanks")
    public JAXBElement<GetBanks> createGetBanks(GetBanks value) {
        return new JAXBElement<GetBanks>(_GetBanks_QNAME, GetBanks.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubmitTransactionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.banking.mobile.esolutions.co.zw/", name = "submitTransactionResponse")
    public JAXBElement<SubmitTransactionResponse> createSubmitTransactionResponse(SubmitTransactionResponse value) {
        return new JAXBElement<SubmitTransactionResponse>(_SubmitTransactionResponse_QNAME, SubmitTransactionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMerchantsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.banking.mobile.esolutions.co.zw/", name = "getMerchantsResponse")
    public JAXBElement<GetMerchantsResponse> createGetMerchantsResponse(GetMerchantsResponse value) {
        return new JAXBElement<GetMerchantsResponse>(_GetMerchantsResponse_QNAME, GetMerchantsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubmitTransaction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.banking.mobile.esolutions.co.zw/", name = "submitTransaction")
    public JAXBElement<SubmitTransaction> createSubmitTransaction(SubmitTransaction value) {
        return new JAXBElement<SubmitTransaction>(_SubmitTransaction_QNAME, SubmitTransaction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMerchants }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.banking.mobile.esolutions.co.zw/", name = "getMerchants")
    public JAXBElement<GetMerchants> createGetMerchants(GetMerchants value) {
        return new JAXBElement<GetMerchants>(_GetMerchants_QNAME, GetMerchants.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VerifyPasswordResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.banking.mobile.esolutions.co.zw/", name = "verifyPasswordResponse")
    public JAXBElement<VerifyPasswordResponse> createVerifyPasswordResponse(VerifyPasswordResponse value) {
        return new JAXBElement<VerifyPasswordResponse>(_VerifyPasswordResponse_QNAME, VerifyPasswordResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VerifyPassword }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.banking.mobile.esolutions.co.zw/", name = "verifyPassword")
    public JAXBElement<VerifyPassword> createVerifyPassword(VerifyPassword value) {
        return new JAXBElement<VerifyPassword>(_VerifyPassword_QNAME, VerifyPassword.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VerifyEnrolment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.banking.mobile.esolutions.co.zw/", name = "verifyEnrolment")
    public JAXBElement<VerifyEnrolment> createVerifyEnrolment(VerifyEnrolment value) {
        return new JAXBElement<VerifyEnrolment>(_VerifyEnrolment_QNAME, VerifyEnrolment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VerifyEnrolmentResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.banking.mobile.esolutions.co.zw/", name = "verifyEnrolmentResponse")
    public JAXBElement<VerifyEnrolmentResponse> createVerifyEnrolmentResponse(VerifyEnrolmentResponse value) {
        return new JAXBElement<VerifyEnrolmentResponse>(_VerifyEnrolmentResponse_QNAME, VerifyEnrolmentResponse.class, null, value);
    }

}
