//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.alertsservices.service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the zw.co.esolutions.ewallet.alertsservices.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FindAlertOptionById_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "findAlertOptionById");
    private final static QName _DisableAlertOption_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "disableAlertOption");
    private final static QName _EditAlertOptionResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "editAlertOptionResponse");
    private final static QName _DeleteTransactionTypeResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "deleteTransactionTypeResponse");
    private final static QName _EnableAlertOption_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "enableAlertOption");
    private final static QName _CreateAlertOptionsForAccountResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "createAlertOptionsForAccountResponse");
    private final static QName _GetTransactionTypeByCodeResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getTransactionTypeByCodeResponse");
    private final static QName _GetAlertOptionByStatusResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getAlertOptionByStatusResponse");
    private final static QName _ApproveAlertOption_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "approveAlertOption");
    private final static QName _GetAlertOptionByBankAccountId_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getAlertOptionByBankAccountId");
    private final static QName _RejectTransactionTypeResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "rejectTransactionTypeResponse");
    private final static QName _CreateTransactionTypeResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "createTransactionTypeResponse");
    private final static QName _GetAlertOptionByBankAccountAndMobileProfileAndTransactionType_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getAlertOptionByBankAccountAndMobileProfileAndTransactionType");
    private final static QName _FindAlertOptionByIdResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "findAlertOptionByIdResponse");
    private final static QName _GetTransactionTypeByStatus_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getTransactionTypeByStatus");
    private final static QName _DisableAlertOptionResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "disableAlertOptionResponse");
    private final static QName _EnableAlertOptionResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "enableAlertOptionResponse");
    private final static QName _EditTransactionType_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "editTransactionType");
    private final static QName _DeleteAlertOption_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "deleteAlertOption");
    private final static QName _GetAllTransactionTypes_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getAllTransactionTypes");
    private final static QName _ApproveAlertOptionResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "approveAlertOptionResponse");
    private final static QName _GetAlertOptionByBankAccountIdResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getAlertOptionByBankAccountIdResponse");
    private final static QName _RejectAlertOption_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "rejectAlertOption");
    private final static QName _GetAlertOptionByBankAccountAndMobileProfileAndTransactionTypeResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getAlertOptionByBankAccountAndMobileProfileAndTransactionTypeResponse");
    private final static QName _GetAlertOptionByMobileProfileId_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getAlertOptionByMobileProfileId");
    private final static QName _CreateAlertOption_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "createAlertOption");
    private final static QName _ApproveTransactionType_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "approveTransactionType");
    private final static QName _Exception_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "Exception");
    private final static QName _EditTransactionTypeResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "editTransactionTypeResponse");
    private final static QName _GetTransactionTypeByStatusResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getTransactionTypeByStatusResponse");
    private final static QName _FindTransactionTypeResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "findTransactionTypeResponse");
    private final static QName _GetAllTransactionTypesResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getAllTransactionTypesResponse");
    private final static QName _DeleteAlertOptionResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "deleteAlertOptionResponse");
    private final static QName _GetTransactionTypeByAlertOption_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getTransactionTypeByAlertOption");
    private final static QName _FindTransactionType_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "findTransactionType");
    private final static QName _RejectAlertOptionResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "rejectAlertOptionResponse");
    private final static QName _GetAlertOptionByMobileProfileIdResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getAlertOptionByMobileProfileIdResponse");
    private final static QName _DisableTransactionType_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "disableTransactionType");
    private final static QName _CreateAlertOptionResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "createAlertOptionResponse");
    private final static QName _EnableTransactionType_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "enableTransactionType");
    private final static QName _GetAlertOptionByTransationTypeId_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getAlertOptionByTransationTypeId");
    private final static QName _DeleteTransactionType_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "deleteTransactionType");
    private final static QName _ApproveTransactionTypeResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "approveTransactionTypeResponse");
    private final static QName _CreateAlertOptionsForAccount_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "createAlertOptionsForAccount");
    private final static QName _EditAlertOption_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "editAlertOption");
    private final static QName _GetTransactionTypeByCode_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getTransactionTypeByCode");
    private final static QName _GetAlertOptionByStatus_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getAlertOptionByStatus");
    private final static QName _RejectTransactionType_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "rejectTransactionType");
    private final static QName _GetTransactionTypeByAlertOptionResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getTransactionTypeByAlertOptionResponse");
    private final static QName _CreateTransactionType_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "createTransactionType");
    private final static QName _DisableTransactionTypeResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "disableTransactionTypeResponse");
    private final static QName _EnableTransactionTypeResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "enableTransactionTypeResponse");
    private final static QName _GetAlertOptionByTransationTypeIdResponse_QNAME = new QName("http://service.alertsservices.ewallet.esolutions.co.zw/", "getAlertOptionByTransationTypeIdResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: zw.co.esolutions.ewallet.alertsservices.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RejectAlertOption }
     * 
     */
    public RejectAlertOption createRejectAlertOption() {
        return new RejectAlertOption();
    }

    /**
     * Create an instance of {@link GetAlertOptionByBankAccountIdResponse }
     * 
     */
    public GetAlertOptionByBankAccountIdResponse createGetAlertOptionByBankAccountIdResponse() {
        return new GetAlertOptionByBankAccountIdResponse();
    }

    /**
     * Create an instance of {@link EnableAlertOptionResponse }
     * 
     */
    public EnableAlertOptionResponse createEnableAlertOptionResponse() {
        return new EnableAlertOptionResponse();
    }

    /**
     * Create an instance of {@link DisableAlertOption }
     * 
     */
    public DisableAlertOption createDisableAlertOption() {
        return new DisableAlertOption();
    }

    /**
     * Create an instance of {@link GetAlertOptionByMobileProfileIdResponse }
     * 
     */
    public GetAlertOptionByMobileProfileIdResponse createGetAlertOptionByMobileProfileIdResponse() {
        return new GetAlertOptionByMobileProfileIdResponse();
    }

    /**
     * Create an instance of {@link DeleteAlertOptionResponse }
     * 
     */
    public DeleteAlertOptionResponse createDeleteAlertOptionResponse() {
        return new DeleteAlertOptionResponse();
    }

    /**
     * Create an instance of {@link GetAlertOptionByBankAccountAndMobileProfileAndTransactionType }
     * 
     */
    public GetAlertOptionByBankAccountAndMobileProfileAndTransactionType createGetAlertOptionByBankAccountAndMobileProfileAndTransactionType() {
        return new GetAlertOptionByBankAccountAndMobileProfileAndTransactionType();
    }

    /**
     * Create an instance of {@link CreateAlertOptionsForAccountResponse }
     * 
     */
    public CreateAlertOptionsForAccountResponse createCreateAlertOptionsForAccountResponse() {
        return new CreateAlertOptionsForAccountResponse();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link FindTransactionType }
     * 
     */
    public FindTransactionType createFindTransactionType() {
        return new FindTransactionType();
    }

    /**
     * Create an instance of {@link EditTransactionType }
     * 
     */
    public EditTransactionType createEditTransactionType() {
        return new EditTransactionType();
    }

    /**
     * Create an instance of {@link GetAlertOptionByTransationTypeId }
     * 
     */
    public GetAlertOptionByTransationTypeId createGetAlertOptionByTransationTypeId() {
        return new GetAlertOptionByTransationTypeId();
    }

    /**
     * Create an instance of {@link GetTransactionTypeByCode }
     * 
     */
    public GetTransactionTypeByCode createGetTransactionTypeByCode() {
        return new GetTransactionTypeByCode();
    }

    /**
     * Create an instance of {@link EditAlertOptionResponse }
     * 
     */
    public EditAlertOptionResponse createEditAlertOptionResponse() {
        return new EditAlertOptionResponse();
    }

    /**
     * Create an instance of {@link RejectAlertOptionResponse }
     * 
     */
    public RejectAlertOptionResponse createRejectAlertOptionResponse() {
        return new RejectAlertOptionResponse();
    }

    /**
     * Create an instance of {@link GetAlertOptionByStatus }
     * 
     */
    public GetAlertOptionByStatus createGetAlertOptionByStatus() {
        return new GetAlertOptionByStatus();
    }

    /**
     * Create an instance of {@link AlertOption }
     * 
     */
    public AlertOption createAlertOption() {
        return new AlertOption();
    }

    /**
     * Create an instance of {@link CreateAlertOptionsForAccount }
     * 
     */
    public CreateAlertOptionsForAccount createCreateAlertOptionsForAccount() {
        return new CreateAlertOptionsForAccount();
    }

    /**
     * Create an instance of {@link GetTransactionTypeByAlertOption }
     * 
     */
    public GetTransactionTypeByAlertOption createGetTransactionTypeByAlertOption() {
        return new GetTransactionTypeByAlertOption();
    }

    /**
     * Create an instance of {@link GetTransactionTypeByStatus }
     * 
     */
    public GetTransactionTypeByStatus createGetTransactionTypeByStatus() {
        return new GetTransactionTypeByStatus();
    }

    /**
     * Create an instance of {@link GetAlertOptionByBankAccountAndMobileProfileAndTransactionTypeResponse }
     * 
     */
    public GetAlertOptionByBankAccountAndMobileProfileAndTransactionTypeResponse createGetAlertOptionByBankAccountAndMobileProfileAndTransactionTypeResponse() {
        return new GetAlertOptionByBankAccountAndMobileProfileAndTransactionTypeResponse();
    }

    /**
     * Create an instance of {@link GetTransactionTypeByCodeResponse }
     * 
     */
    public GetTransactionTypeByCodeResponse createGetTransactionTypeByCodeResponse() {
        return new GetTransactionTypeByCodeResponse();
    }

    /**
     * Create an instance of {@link RejectTransactionType }
     * 
     */
    public RejectTransactionType createRejectTransactionType() {
        return new RejectTransactionType();
    }

    /**
     * Create an instance of {@link GetAlertOptionByStatusResponse }
     * 
     */
    public GetAlertOptionByStatusResponse createGetAlertOptionByStatusResponse() {
        return new GetAlertOptionByStatusResponse();
    }

    /**
     * Create an instance of {@link FindAlertOptionByIdResponse }
     * 
     */
    public FindAlertOptionByIdResponse createFindAlertOptionByIdResponse() {
        return new FindAlertOptionByIdResponse();
    }

    /**
     * Create an instance of {@link EditTransactionTypeResponse }
     * 
     */
    public EditTransactionTypeResponse createEditTransactionTypeResponse() {
        return new EditTransactionTypeResponse();
    }

    /**
     * Create an instance of {@link CreateTransactionTypeResponse }
     * 
     */
    public CreateTransactionTypeResponse createCreateTransactionTypeResponse() {
        return new CreateTransactionTypeResponse();
    }

    /**
     * Create an instance of {@link CreateTransactionType }
     * 
     */
    public CreateTransactionType createCreateTransactionType() {
        return new CreateTransactionType();
    }

    /**
     * Create an instance of {@link GetTransactionTypeByAlertOptionResponse }
     * 
     */
    public GetTransactionTypeByAlertOptionResponse createGetTransactionTypeByAlertOptionResponse() {
        return new GetTransactionTypeByAlertOptionResponse();
    }

    /**
     * Create an instance of {@link ApproveAlertOption }
     * 
     */
    public ApproveAlertOption createApproveAlertOption() {
        return new ApproveAlertOption();
    }

    /**
     * Create an instance of {@link DisableAlertOptionResponse }
     * 
     */
    public DisableAlertOptionResponse createDisableAlertOptionResponse() {
        return new DisableAlertOptionResponse();
    }

    /**
     * Create an instance of {@link DeleteTransactionType }
     * 
     */
    public DeleteTransactionType createDeleteTransactionType() {
        return new DeleteTransactionType();
    }

    /**
     * Create an instance of {@link EnableTransactionTypeResponse }
     * 
     */
    public EnableTransactionTypeResponse createEnableTransactionTypeResponse() {
        return new EnableTransactionTypeResponse();
    }

    /**
     * Create an instance of {@link DisableTransactionTypeResponse }
     * 
     */
    public DisableTransactionTypeResponse createDisableTransactionTypeResponse() {
        return new DisableTransactionTypeResponse();
    }

    /**
     * Create an instance of {@link GetTransactionTypeByStatusResponse }
     * 
     */
    public GetTransactionTypeByStatusResponse createGetTransactionTypeByStatusResponse() {
        return new GetTransactionTypeByStatusResponse();
    }

    /**
     * Create an instance of {@link GetAlertOptionByBankAccountId }
     * 
     */
    public GetAlertOptionByBankAccountId createGetAlertOptionByBankAccountId() {
        return new GetAlertOptionByBankAccountId();
    }

    /**
     * Create an instance of {@link DeleteTransactionTypeResponse }
     * 
     */
    public DeleteTransactionTypeResponse createDeleteTransactionTypeResponse() {
        return new DeleteTransactionTypeResponse();
    }

    /**
     * Create an instance of {@link GetAllTransactionTypes }
     * 
     */
    public GetAllTransactionTypes createGetAllTransactionTypes() {
        return new GetAllTransactionTypes();
    }

    /**
     * Create an instance of {@link TransactionType }
     * 
     */
    public TransactionType createTransactionType() {
        return new TransactionType();
    }

    /**
     * Create an instance of {@link RejectTransactionTypeResponse }
     * 
     */
    public RejectTransactionTypeResponse createRejectTransactionTypeResponse() {
        return new RejectTransactionTypeResponse();
    }

    /**
     * Create an instance of {@link ApproveTransactionTypeResponse }
     * 
     */
    public ApproveTransactionTypeResponse createApproveTransactionTypeResponse() {
        return new ApproveTransactionTypeResponse();
    }

    /**
     * Create an instance of {@link ApproveTransactionType }
     * 
     */
    public ApproveTransactionType createApproveTransactionType() {
        return new ApproveTransactionType();
    }

    /**
     * Create an instance of {@link EnableAlertOption }
     * 
     */
    public EnableAlertOption createEnableAlertOption() {
        return new EnableAlertOption();
    }

    /**
     * Create an instance of {@link GetAlertOptionByTransationTypeIdResponse }
     * 
     */
    public GetAlertOptionByTransationTypeIdResponse createGetAlertOptionByTransationTypeIdResponse() {
        return new GetAlertOptionByTransationTypeIdResponse();
    }

    /**
     * Create an instance of {@link DeleteAlertOption }
     * 
     */
    public DeleteAlertOption createDeleteAlertOption() {
        return new DeleteAlertOption();
    }

    /**
     * Create an instance of {@link CreateAlertOptionResponse }
     * 
     */
    public CreateAlertOptionResponse createCreateAlertOptionResponse() {
        return new CreateAlertOptionResponse();
    }

    /**
     * Create an instance of {@link CreateAlertOption }
     * 
     */
    public CreateAlertOption createCreateAlertOption() {
        return new CreateAlertOption();
    }

    /**
     * Create an instance of {@link EditAlertOption }
     * 
     */
    public EditAlertOption createEditAlertOption() {
        return new EditAlertOption();
    }

    /**
     * Create an instance of {@link FindAlertOptionById }
     * 
     */
    public FindAlertOptionById createFindAlertOptionById() {
        return new FindAlertOptionById();
    }

    /**
     * Create an instance of {@link DisableTransactionType }
     * 
     */
    public DisableTransactionType createDisableTransactionType() {
        return new DisableTransactionType();
    }

    /**
     * Create an instance of {@link FindTransactionTypeResponse }
     * 
     */
    public FindTransactionTypeResponse createFindTransactionTypeResponse() {
        return new FindTransactionTypeResponse();
    }

    /**
     * Create an instance of {@link GetAllTransactionTypesResponse }
     * 
     */
    public GetAllTransactionTypesResponse createGetAllTransactionTypesResponse() {
        return new GetAllTransactionTypesResponse();
    }

    /**
     * Create an instance of {@link GetAlertOptionByMobileProfileId }
     * 
     */
    public GetAlertOptionByMobileProfileId createGetAlertOptionByMobileProfileId() {
        return new GetAlertOptionByMobileProfileId();
    }

    /**
     * Create an instance of {@link EnableTransactionType }
     * 
     */
    public EnableTransactionType createEnableTransactionType() {
        return new EnableTransactionType();
    }

    /**
     * Create an instance of {@link ApproveAlertOptionResponse }
     * 
     */
    public ApproveAlertOptionResponse createApproveAlertOptionResponse() {
        return new ApproveAlertOptionResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindAlertOptionById }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "findAlertOptionById")
    public JAXBElement<FindAlertOptionById> createFindAlertOptionById(FindAlertOptionById value) {
        return new JAXBElement<FindAlertOptionById>(_FindAlertOptionById_QNAME, FindAlertOptionById.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DisableAlertOption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "disableAlertOption")
    public JAXBElement<DisableAlertOption> createDisableAlertOption(DisableAlertOption value) {
        return new JAXBElement<DisableAlertOption>(_DisableAlertOption_QNAME, DisableAlertOption.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditAlertOptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "editAlertOptionResponse")
    public JAXBElement<EditAlertOptionResponse> createEditAlertOptionResponse(EditAlertOptionResponse value) {
        return new JAXBElement<EditAlertOptionResponse>(_EditAlertOptionResponse_QNAME, EditAlertOptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteTransactionTypeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "deleteTransactionTypeResponse")
    public JAXBElement<DeleteTransactionTypeResponse> createDeleteTransactionTypeResponse(DeleteTransactionTypeResponse value) {
        return new JAXBElement<DeleteTransactionTypeResponse>(_DeleteTransactionTypeResponse_QNAME, DeleteTransactionTypeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnableAlertOption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "enableAlertOption")
    public JAXBElement<EnableAlertOption> createEnableAlertOption(EnableAlertOption value) {
        return new JAXBElement<EnableAlertOption>(_EnableAlertOption_QNAME, EnableAlertOption.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAlertOptionsForAccountResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "createAlertOptionsForAccountResponse")
    public JAXBElement<CreateAlertOptionsForAccountResponse> createCreateAlertOptionsForAccountResponse(CreateAlertOptionsForAccountResponse value) {
        return new JAXBElement<CreateAlertOptionsForAccountResponse>(_CreateAlertOptionsForAccountResponse_QNAME, CreateAlertOptionsForAccountResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTransactionTypeByCodeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getTransactionTypeByCodeResponse")
    public JAXBElement<GetTransactionTypeByCodeResponse> createGetTransactionTypeByCodeResponse(GetTransactionTypeByCodeResponse value) {
        return new JAXBElement<GetTransactionTypeByCodeResponse>(_GetTransactionTypeByCodeResponse_QNAME, GetTransactionTypeByCodeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAlertOptionByStatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getAlertOptionByStatusResponse")
    public JAXBElement<GetAlertOptionByStatusResponse> createGetAlertOptionByStatusResponse(GetAlertOptionByStatusResponse value) {
        return new JAXBElement<GetAlertOptionByStatusResponse>(_GetAlertOptionByStatusResponse_QNAME, GetAlertOptionByStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApproveAlertOption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "approveAlertOption")
    public JAXBElement<ApproveAlertOption> createApproveAlertOption(ApproveAlertOption value) {
        return new JAXBElement<ApproveAlertOption>(_ApproveAlertOption_QNAME, ApproveAlertOption.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAlertOptionByBankAccountId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getAlertOptionByBankAccountId")
    public JAXBElement<GetAlertOptionByBankAccountId> createGetAlertOptionByBankAccountId(GetAlertOptionByBankAccountId value) {
        return new JAXBElement<GetAlertOptionByBankAccountId>(_GetAlertOptionByBankAccountId_QNAME, GetAlertOptionByBankAccountId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RejectTransactionTypeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "rejectTransactionTypeResponse")
    public JAXBElement<RejectTransactionTypeResponse> createRejectTransactionTypeResponse(RejectTransactionTypeResponse value) {
        return new JAXBElement<RejectTransactionTypeResponse>(_RejectTransactionTypeResponse_QNAME, RejectTransactionTypeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateTransactionTypeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "createTransactionTypeResponse")
    public JAXBElement<CreateTransactionTypeResponse> createCreateTransactionTypeResponse(CreateTransactionTypeResponse value) {
        return new JAXBElement<CreateTransactionTypeResponse>(_CreateTransactionTypeResponse_QNAME, CreateTransactionTypeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAlertOptionByBankAccountAndMobileProfileAndTransactionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getAlertOptionByBankAccountAndMobileProfileAndTransactionType")
    public JAXBElement<GetAlertOptionByBankAccountAndMobileProfileAndTransactionType> createGetAlertOptionByBankAccountAndMobileProfileAndTransactionType(GetAlertOptionByBankAccountAndMobileProfileAndTransactionType value) {
        return new JAXBElement<GetAlertOptionByBankAccountAndMobileProfileAndTransactionType>(_GetAlertOptionByBankAccountAndMobileProfileAndTransactionType_QNAME, GetAlertOptionByBankAccountAndMobileProfileAndTransactionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindAlertOptionByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "findAlertOptionByIdResponse")
    public JAXBElement<FindAlertOptionByIdResponse> createFindAlertOptionByIdResponse(FindAlertOptionByIdResponse value) {
        return new JAXBElement<FindAlertOptionByIdResponse>(_FindAlertOptionByIdResponse_QNAME, FindAlertOptionByIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTransactionTypeByStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getTransactionTypeByStatus")
    public JAXBElement<GetTransactionTypeByStatus> createGetTransactionTypeByStatus(GetTransactionTypeByStatus value) {
        return new JAXBElement<GetTransactionTypeByStatus>(_GetTransactionTypeByStatus_QNAME, GetTransactionTypeByStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DisableAlertOptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "disableAlertOptionResponse")
    public JAXBElement<DisableAlertOptionResponse> createDisableAlertOptionResponse(DisableAlertOptionResponse value) {
        return new JAXBElement<DisableAlertOptionResponse>(_DisableAlertOptionResponse_QNAME, DisableAlertOptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnableAlertOptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "enableAlertOptionResponse")
    public JAXBElement<EnableAlertOptionResponse> createEnableAlertOptionResponse(EnableAlertOptionResponse value) {
        return new JAXBElement<EnableAlertOptionResponse>(_EnableAlertOptionResponse_QNAME, EnableAlertOptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditTransactionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "editTransactionType")
    public JAXBElement<EditTransactionType> createEditTransactionType(EditTransactionType value) {
        return new JAXBElement<EditTransactionType>(_EditTransactionType_QNAME, EditTransactionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteAlertOption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "deleteAlertOption")
    public JAXBElement<DeleteAlertOption> createDeleteAlertOption(DeleteAlertOption value) {
        return new JAXBElement<DeleteAlertOption>(_DeleteAlertOption_QNAME, DeleteAlertOption.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllTransactionTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getAllTransactionTypes")
    public JAXBElement<GetAllTransactionTypes> createGetAllTransactionTypes(GetAllTransactionTypes value) {
        return new JAXBElement<GetAllTransactionTypes>(_GetAllTransactionTypes_QNAME, GetAllTransactionTypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApproveAlertOptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "approveAlertOptionResponse")
    public JAXBElement<ApproveAlertOptionResponse> createApproveAlertOptionResponse(ApproveAlertOptionResponse value) {
        return new JAXBElement<ApproveAlertOptionResponse>(_ApproveAlertOptionResponse_QNAME, ApproveAlertOptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAlertOptionByBankAccountIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getAlertOptionByBankAccountIdResponse")
    public JAXBElement<GetAlertOptionByBankAccountIdResponse> createGetAlertOptionByBankAccountIdResponse(GetAlertOptionByBankAccountIdResponse value) {
        return new JAXBElement<GetAlertOptionByBankAccountIdResponse>(_GetAlertOptionByBankAccountIdResponse_QNAME, GetAlertOptionByBankAccountIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RejectAlertOption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "rejectAlertOption")
    public JAXBElement<RejectAlertOption> createRejectAlertOption(RejectAlertOption value) {
        return new JAXBElement<RejectAlertOption>(_RejectAlertOption_QNAME, RejectAlertOption.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAlertOptionByBankAccountAndMobileProfileAndTransactionTypeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getAlertOptionByBankAccountAndMobileProfileAndTransactionTypeResponse")
    public JAXBElement<GetAlertOptionByBankAccountAndMobileProfileAndTransactionTypeResponse> createGetAlertOptionByBankAccountAndMobileProfileAndTransactionTypeResponse(GetAlertOptionByBankAccountAndMobileProfileAndTransactionTypeResponse value) {
        return new JAXBElement<GetAlertOptionByBankAccountAndMobileProfileAndTransactionTypeResponse>(_GetAlertOptionByBankAccountAndMobileProfileAndTransactionTypeResponse_QNAME, GetAlertOptionByBankAccountAndMobileProfileAndTransactionTypeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAlertOptionByMobileProfileId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getAlertOptionByMobileProfileId")
    public JAXBElement<GetAlertOptionByMobileProfileId> createGetAlertOptionByMobileProfileId(GetAlertOptionByMobileProfileId value) {
        return new JAXBElement<GetAlertOptionByMobileProfileId>(_GetAlertOptionByMobileProfileId_QNAME, GetAlertOptionByMobileProfileId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAlertOption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "createAlertOption")
    public JAXBElement<CreateAlertOption> createCreateAlertOption(CreateAlertOption value) {
        return new JAXBElement<CreateAlertOption>(_CreateAlertOption_QNAME, CreateAlertOption.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApproveTransactionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "approveTransactionType")
    public JAXBElement<ApproveTransactionType> createApproveTransactionType(ApproveTransactionType value) {
        return new JAXBElement<ApproveTransactionType>(_ApproveTransactionType_QNAME, ApproveTransactionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "Exception")
    public JAXBElement<Exception> createException(Exception value) {
        return new JAXBElement<Exception>(_Exception_QNAME, Exception.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditTransactionTypeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "editTransactionTypeResponse")
    public JAXBElement<EditTransactionTypeResponse> createEditTransactionTypeResponse(EditTransactionTypeResponse value) {
        return new JAXBElement<EditTransactionTypeResponse>(_EditTransactionTypeResponse_QNAME, EditTransactionTypeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTransactionTypeByStatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getTransactionTypeByStatusResponse")
    public JAXBElement<GetTransactionTypeByStatusResponse> createGetTransactionTypeByStatusResponse(GetTransactionTypeByStatusResponse value) {
        return new JAXBElement<GetTransactionTypeByStatusResponse>(_GetTransactionTypeByStatusResponse_QNAME, GetTransactionTypeByStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindTransactionTypeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "findTransactionTypeResponse")
    public JAXBElement<FindTransactionTypeResponse> createFindTransactionTypeResponse(FindTransactionTypeResponse value) {
        return new JAXBElement<FindTransactionTypeResponse>(_FindTransactionTypeResponse_QNAME, FindTransactionTypeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllTransactionTypesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getAllTransactionTypesResponse")
    public JAXBElement<GetAllTransactionTypesResponse> createGetAllTransactionTypesResponse(GetAllTransactionTypesResponse value) {
        return new JAXBElement<GetAllTransactionTypesResponse>(_GetAllTransactionTypesResponse_QNAME, GetAllTransactionTypesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteAlertOptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "deleteAlertOptionResponse")
    public JAXBElement<DeleteAlertOptionResponse> createDeleteAlertOptionResponse(DeleteAlertOptionResponse value) {
        return new JAXBElement<DeleteAlertOptionResponse>(_DeleteAlertOptionResponse_QNAME, DeleteAlertOptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTransactionTypeByAlertOption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getTransactionTypeByAlertOption")
    public JAXBElement<GetTransactionTypeByAlertOption> createGetTransactionTypeByAlertOption(GetTransactionTypeByAlertOption value) {
        return new JAXBElement<GetTransactionTypeByAlertOption>(_GetTransactionTypeByAlertOption_QNAME, GetTransactionTypeByAlertOption.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindTransactionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "findTransactionType")
    public JAXBElement<FindTransactionType> createFindTransactionType(FindTransactionType value) {
        return new JAXBElement<FindTransactionType>(_FindTransactionType_QNAME, FindTransactionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RejectAlertOptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "rejectAlertOptionResponse")
    public JAXBElement<RejectAlertOptionResponse> createRejectAlertOptionResponse(RejectAlertOptionResponse value) {
        return new JAXBElement<RejectAlertOptionResponse>(_RejectAlertOptionResponse_QNAME, RejectAlertOptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAlertOptionByMobileProfileIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getAlertOptionByMobileProfileIdResponse")
    public JAXBElement<GetAlertOptionByMobileProfileIdResponse> createGetAlertOptionByMobileProfileIdResponse(GetAlertOptionByMobileProfileIdResponse value) {
        return new JAXBElement<GetAlertOptionByMobileProfileIdResponse>(_GetAlertOptionByMobileProfileIdResponse_QNAME, GetAlertOptionByMobileProfileIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DisableTransactionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "disableTransactionType")
    public JAXBElement<DisableTransactionType> createDisableTransactionType(DisableTransactionType value) {
        return new JAXBElement<DisableTransactionType>(_DisableTransactionType_QNAME, DisableTransactionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAlertOptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "createAlertOptionResponse")
    public JAXBElement<CreateAlertOptionResponse> createCreateAlertOptionResponse(CreateAlertOptionResponse value) {
        return new JAXBElement<CreateAlertOptionResponse>(_CreateAlertOptionResponse_QNAME, CreateAlertOptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnableTransactionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "enableTransactionType")
    public JAXBElement<EnableTransactionType> createEnableTransactionType(EnableTransactionType value) {
        return new JAXBElement<EnableTransactionType>(_EnableTransactionType_QNAME, EnableTransactionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAlertOptionByTransationTypeId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getAlertOptionByTransationTypeId")
    public JAXBElement<GetAlertOptionByTransationTypeId> createGetAlertOptionByTransationTypeId(GetAlertOptionByTransationTypeId value) {
        return new JAXBElement<GetAlertOptionByTransationTypeId>(_GetAlertOptionByTransationTypeId_QNAME, GetAlertOptionByTransationTypeId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteTransactionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "deleteTransactionType")
    public JAXBElement<DeleteTransactionType> createDeleteTransactionType(DeleteTransactionType value) {
        return new JAXBElement<DeleteTransactionType>(_DeleteTransactionType_QNAME, DeleteTransactionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApproveTransactionTypeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "approveTransactionTypeResponse")
    public JAXBElement<ApproveTransactionTypeResponse> createApproveTransactionTypeResponse(ApproveTransactionTypeResponse value) {
        return new JAXBElement<ApproveTransactionTypeResponse>(_ApproveTransactionTypeResponse_QNAME, ApproveTransactionTypeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAlertOptionsForAccount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "createAlertOptionsForAccount")
    public JAXBElement<CreateAlertOptionsForAccount> createCreateAlertOptionsForAccount(CreateAlertOptionsForAccount value) {
        return new JAXBElement<CreateAlertOptionsForAccount>(_CreateAlertOptionsForAccount_QNAME, CreateAlertOptionsForAccount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditAlertOption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "editAlertOption")
    public JAXBElement<EditAlertOption> createEditAlertOption(EditAlertOption value) {
        return new JAXBElement<EditAlertOption>(_EditAlertOption_QNAME, EditAlertOption.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTransactionTypeByCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getTransactionTypeByCode")
    public JAXBElement<GetTransactionTypeByCode> createGetTransactionTypeByCode(GetTransactionTypeByCode value) {
        return new JAXBElement<GetTransactionTypeByCode>(_GetTransactionTypeByCode_QNAME, GetTransactionTypeByCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAlertOptionByStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getAlertOptionByStatus")
    public JAXBElement<GetAlertOptionByStatus> createGetAlertOptionByStatus(GetAlertOptionByStatus value) {
        return new JAXBElement<GetAlertOptionByStatus>(_GetAlertOptionByStatus_QNAME, GetAlertOptionByStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RejectTransactionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "rejectTransactionType")
    public JAXBElement<RejectTransactionType> createRejectTransactionType(RejectTransactionType value) {
        return new JAXBElement<RejectTransactionType>(_RejectTransactionType_QNAME, RejectTransactionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTransactionTypeByAlertOptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getTransactionTypeByAlertOptionResponse")
    public JAXBElement<GetTransactionTypeByAlertOptionResponse> createGetTransactionTypeByAlertOptionResponse(GetTransactionTypeByAlertOptionResponse value) {
        return new JAXBElement<GetTransactionTypeByAlertOptionResponse>(_GetTransactionTypeByAlertOptionResponse_QNAME, GetTransactionTypeByAlertOptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateTransactionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "createTransactionType")
    public JAXBElement<CreateTransactionType> createCreateTransactionType(CreateTransactionType value) {
        return new JAXBElement<CreateTransactionType>(_CreateTransactionType_QNAME, CreateTransactionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DisableTransactionTypeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "disableTransactionTypeResponse")
    public JAXBElement<DisableTransactionTypeResponse> createDisableTransactionTypeResponse(DisableTransactionTypeResponse value) {
        return new JAXBElement<DisableTransactionTypeResponse>(_DisableTransactionTypeResponse_QNAME, DisableTransactionTypeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnableTransactionTypeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "enableTransactionTypeResponse")
    public JAXBElement<EnableTransactionTypeResponse> createEnableTransactionTypeResponse(EnableTransactionTypeResponse value) {
        return new JAXBElement<EnableTransactionTypeResponse>(_EnableTransactionTypeResponse_QNAME, EnableTransactionTypeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAlertOptionByTransationTypeIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.alertsservices.ewallet.esolutions.co.zw/", name = "getAlertOptionByTransationTypeIdResponse")
    public JAXBElement<GetAlertOptionByTransationTypeIdResponse> createGetAlertOptionByTransationTypeIdResponse(GetAlertOptionByTransationTypeIdResponse value) {
        return new JAXBElement<GetAlertOptionByTransationTypeIdResponse>(_GetAlertOptionByTransationTypeIdResponse_QNAME, GetAlertOptionByTransationTypeIdResponse.class, null, value);
    }

}
