//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.27 at 08:41:07 PM SAST 
//


package zw.co.esolutions.config.merchant;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the zw.co.esolutions.config.merchant package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MerchantInfo_QNAME = new QName("http://merchant.config.esolutions.co.zw", "merchantInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: zw.co.esolutions.config.merchant
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MerchantInfo }
     * 
     */
    public MerchantInfo createMerchantInfo() {
        return new MerchantInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MerchantInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://merchant.config.esolutions.co.zw", name = "merchantInfo")
    public JAXBElement<MerchantInfo> createMerchantInfo(MerchantInfo value) {
        return new JAXBElement<MerchantInfo>(_MerchantInfo_QNAME, MerchantInfo.class, null, value);
    }

}
