//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4)
//


package zw.co.esolutions.ussd.web.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "MobileCommerceService", targetNamespace = "http://services.web.ussd.esolutions.co.zw/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MobileCommerceService {


    /**
     * 
     * @param ussdTransaction
     * @return
     *     returns zw.co.esolutions.ussd.web.services.UssdTransaction
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTransaction", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.CreateTransaction")
    @ResponseWrapper(localName = "createTransactionResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.CreateTransactionResponse")
    public UssdTransaction createTransaction(
        @WebParam(name = "ussdTransaction", targetNamespace = "")
        UssdTransaction ussdTransaction)
        throws Exception_Exception
    ;

    /**
     * 
     * @param ussdTransaction
     * @return
     *     returns zw.co.esolutions.ussd.web.services.UssdTransaction
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateTransaction", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.UpdateTransaction")
    @ResponseWrapper(localName = "updateTransactionResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.UpdateTransactionResponse")
    public UssdTransaction updateTransaction(
        @WebParam(name = "ussdTransaction", targetNamespace = "")
        UssdTransaction ussdTransaction)
        throws Exception_Exception
    ;

    /**
     * 
     * @param uuid
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteTransaction", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.DeleteTransaction")
    @ResponseWrapper(localName = "deleteTransactionResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.DeleteTransactionResponse")
    public void deleteTransaction(
        @WebParam(name = "uuid", targetNamespace = "")
        String uuid)
        throws Exception_Exception
    ;

    /**
     * 
     * @param uuid
     * @return
     *     returns zw.co.esolutions.ussd.web.services.UssdTransaction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findTransaction", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.FindTransaction")
    @ResponseWrapper(localName = "findTransactionResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.FindTransactionResponse")
    public UssdTransaction findTransaction(
        @WebParam(name = "uuid", targetNamespace = "")
        String uuid);

    /**
     * 
     * @param ussdSessionId
     * @return
     *     returns zw.co.esolutions.ussd.web.services.UssdTransaction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransactionByUSSDSessionId", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.GetTransactionByUSSDSessionId")
    @ResponseWrapper(localName = "getTransactionByUSSDSessionIdResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.GetTransactionByUSSDSessionIdResponse")
    public UssdTransaction getTransactionByUSSDSessionId(
        @WebParam(name = "ussdSessionId", targetNamespace = "")
        String ussdSessionId);

    /**
     * 
     * @param webSession
     * @return
     *     returns zw.co.esolutions.ussd.web.services.WebSession
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createWebSession", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.CreateWebSession")
    @ResponseWrapper(localName = "createWebSessionResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.CreateWebSessionResponse")
    public WebSession createWebSession(
        @WebParam(name = "webSession", targetNamespace = "")
        WebSession webSession);

    /**
     * 
     * @param webSessionId
     */
    @WebMethod
    @RequestWrapper(localName = "deleteWebSession", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.DeleteWebSession")
    @ResponseWrapper(localName = "deleteWebSessionResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.DeleteWebSessionResponse")
    public void deleteWebSession(
        @WebParam(name = "webSessionId", targetNamespace = "")
        String webSessionId);

    /**
     * 
     * @param webSessionId
     * @return
     *     returns zw.co.esolutions.ussd.web.services.WebSession
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findWebSessionById", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.FindWebSessionById")
    @ResponseWrapper(localName = "findWebSessionByIdResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.FindWebSessionByIdResponse")
    public WebSession findWebSessionById(
        @WebParam(name = "webSessionId", targetNamespace = "")
        String webSessionId);

    /**
     * 
     * @param bankId
     * @param mobileNumber
     * @return
     *     returns zw.co.esolutions.ussd.web.services.WebSession
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFailedWebSession", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.GetFailedWebSession")
    @ResponseWrapper(localName = "getFailedWebSessionResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.GetFailedWebSessionResponse")
    public WebSession getFailedWebSession(
        @WebParam(name = "mobileNumber", targetNamespace = "")
        String mobileNumber,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param referenceId
     * @return
     *     returns zw.co.esolutions.ussd.web.services.WebSession
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWebSessionByReferenceId", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.GetWebSessionByReferenceId")
    @ResponseWrapper(localName = "getWebSessionByReferenceIdResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.GetWebSessionByReferenceIdResponse")
    public WebSession getWebSessionByReferenceId(
        @WebParam(name = "referenceId", targetNamespace = "")
        String referenceId);

    /**
     * 
     * @param webSession
     * @return
     *     returns zw.co.esolutions.ussd.web.services.WebSession
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateWebSession", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.UpdateWebSession")
    @ResponseWrapper(localName = "updateWebSessionResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.UpdateWebSessionResponse")
    public WebSession updateWebSession(
        @WebParam(name = "webSession", targetNamespace = "")
        WebSession webSession);

    /**
     * 
     * @param status
     * @param bankId
     * @param mobileNumber
     * @return
     *     returns zw.co.esolutions.ussd.web.services.WebSession
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWebSessionByMobileAndBankAndStatus", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.GetWebSessionByMobileAndBankAndStatus")
    @ResponseWrapper(localName = "getWebSessionByMobileAndBankAndStatusResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.GetWebSessionByMobileAndBankAndStatusResponse")
    public WebSession getWebSessionByMobileAndBankAndStatus(
        @WebParam(name = "mobileNumber", targetNamespace = "")
        String mobileNumber,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId,
        @WebParam(name = "status", targetNamespace = "")
        String status);

    /**
     * 
     * @param mobileWebRequest
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendTransaction", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.SendTransaction")
    @ResponseWrapper(localName = "sendTransactionResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.SendTransactionResponse")
    public boolean sendTransaction(
        @WebParam(name = "mobileWebRequest", targetNamespace = "")
        MobileWebRequestMessage mobileWebRequest);

    /**
     * 
     * @param sessionId
     * @param targetMobile
     * @param targetAccount
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTargetBankCodeForTargetAccount", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.GetTargetBankCodeForTargetAccount")
    @ResponseWrapper(localName = "getTargetBankCodeForTargetAccountResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.GetTargetBankCodeForTargetAccountResponse")
    public String getTargetBankCodeForTargetAccount(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "targetAccount", targetNamespace = "")
        String targetAccount,
        @WebParam(name = "targetMobile", targetNamespace = "")
        String targetMobile);

    /**
     * 
     * @param formattedMobileNumber
     * @param bankCode
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isAgentMobile", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.IsAgentMobile")
    @ResponseWrapper(localName = "isAgentMobileResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.IsAgentMobileResponse")
    public boolean isAgentMobile(
        @WebParam(name = "bankCode", targetNamespace = "")
        String bankCode,
        @WebParam(name = "formattedMobileNumber", targetNamespace = "")
        String formattedMobileNumber);

    /**
     * 
     * @param sourceAccount
     * @param targetMobile
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateAgentDeposit", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.ValidateAgentDeposit")
    @ResponseWrapper(localName = "validateAgentDepositResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.ValidateAgentDepositResponse")
    public String validateAgentDeposit(
        @WebParam(name = "sourceAccount", targetNamespace = "")
        String sourceAccount,
        @WebParam(name = "targetMobile", targetNamespace = "")
        String targetMobile);

    /**
     * 
     * @param sourceAccount
     * @param bankCode
     * @param targetAccount
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateAgentTransfer", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.ValidateAgentTransfer")
    @ResponseWrapper(localName = "validateAgentTransferResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.ValidateAgentTransferResponse")
    public String validateAgentTransfer(
        @WebParam(name = "sourceAccount", targetNamespace = "")
        String sourceAccount,
        @WebParam(name = "targetAccount", targetNamespace = "")
        String targetAccount,
        @WebParam(name = "bankCode", targetNamespace = "")
        String bankCode);

    /**
     * 
     * @param targetAccount
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateAgentCustomerWithdrawal", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.ValidateAgentCustomerWithdrawal")
    @ResponseWrapper(localName = "validateAgentCustomerWithdrawalResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.ValidateAgentCustomerWithdrawalResponse")
    public String validateAgentCustomerWithdrawal(
        @WebParam(name = "targetAccount", targetNamespace = "")
        String targetAccount);

    /**
     * 
     * @param bankCode
     * @param mobileNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAgentNumberByMobileNumberAndBankId", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.GetAgentNumberByMobileNumberAndBankId")
    @ResponseWrapper(localName = "getAgentNumberByMobileNumberAndBankIdResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.GetAgentNumberByMobileNumberAndBankIdResponse")
    public String getAgentNumberByMobileNumberAndBankId(
        @WebParam(name = "mobileNumber", targetNamespace = "")
        String mobileNumber,
        @WebParam(name = "bankCode", targetNamespace = "")
        String bankCode);

    /**
     * 
     * @param bankCode
     * @param targetAccount
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isNonHolderAccount", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.IsNonHolderAccount")
    @ResponseWrapper(localName = "isNonHolderAccountResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.IsNonHolderAccountResponse")
    public boolean isNonHolderAccount(
        @WebParam(name = "targetAccount", targetNamespace = "")
        String targetAccount,
        @WebParam(name = "bankCode", targetNamespace = "")
        String bankCode);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActiveBankNames", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.GetActiveBankNames")
    @ResponseWrapper(localName = "getActiveBankNamesResponse", targetNamespace = "http://services.web.ussd.esolutions.co.zw/", className = "zw.co.esolutions.ussd.web.services.GetActiveBankNamesResponse")
    public List<String> getActiveBankNames();

}
