//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4)
//


package zw.co.esolutions.ussd.web.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mobileWebRequestMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mobileWebRequestMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="agentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="beneficiaryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerUtilityAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ddmmyyDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="destinationBankName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mno" type="{http://services.web.ussd.esolutions.co.zw/}mobileNetworkOperator" minOccurs="0"/>
 *         &lt;element name="newPin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="oldPin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="paymentRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="refCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="secretCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sourceBankAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sourceBankId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sourceMobileNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="targetBankAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="targetBankId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="targetMobileNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="transactionType" type="{http://services.web.ussd.esolutions.co.zw/}mobileWebTransactionType" minOccurs="0"/>
 *         &lt;element name="utilityName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mobileWebRequestMessage", propOrder = {
    "agentNumber",
    "amount",
    "beneficiaryName",
    "customerUtilityAccount",
    "ddmmyyDate",
    "destinationBankName",
    "mno",
    "newPin",
    "oldPin",
    "paymentRef",
    "refCode",
    "secretCode",
    "sourceBankAccount",
    "sourceBankId",
    "sourceMobileNumber",
    "targetBankAccount",
    "targetBankId",
    "targetMobileNumber",
    "transactionType",
    "utilityName",
    "uuid"
})
public class MobileWebRequestMessage {

    protected String agentNumber;
    protected long amount;
    protected String beneficiaryName;
    protected String customerUtilityAccount;
    protected String ddmmyyDate;
    protected String destinationBankName;
    protected MobileNetworkOperator mno;
    protected String newPin;
    protected String oldPin;
    protected String paymentRef;
    protected String refCode;
    protected String secretCode;
    protected String sourceBankAccount;
    protected String sourceBankId;
    protected String sourceMobileNumber;
    protected String targetBankAccount;
    protected String targetBankId;
    protected String targetMobileNumber;
    protected MobileWebTransactionType transactionType;
    protected String utilityName;
    protected String uuid;

    /**
     * Gets the value of the agentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentNumber() {
        return agentNumber;
    }

    /**
     * Sets the value of the agentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentNumber(String value) {
        this.agentNumber = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public long getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(long value) {
        this.amount = value;
    }

    /**
     * Gets the value of the beneficiaryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeneficiaryName() {
        return beneficiaryName;
    }

    /**
     * Sets the value of the beneficiaryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeneficiaryName(String value) {
        this.beneficiaryName = value;
    }

    /**
     * Gets the value of the customerUtilityAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerUtilityAccount() {
        return customerUtilityAccount;
    }

    /**
     * Sets the value of the customerUtilityAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerUtilityAccount(String value) {
        this.customerUtilityAccount = value;
    }

    /**
     * Gets the value of the ddmmyyDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDdmmyyDate() {
        return ddmmyyDate;
    }

    /**
     * Sets the value of the ddmmyyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDdmmyyDate(String value) {
        this.ddmmyyDate = value;
    }

    /**
     * Gets the value of the destinationBankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationBankName() {
        return destinationBankName;
    }

    /**
     * Sets the value of the destinationBankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationBankName(String value) {
        this.destinationBankName = value;
    }

    /**
     * Gets the value of the mno property.
     * 
     * @return
     *     possible object is
     *     {@link MobileNetworkOperator }
     *     
     */
    public MobileNetworkOperator getMno() {
        return mno;
    }

    /**
     * Sets the value of the mno property.
     * 
     * @param value
     *     allowed object is
     *     {@link MobileNetworkOperator }
     *     
     */
    public void setMno(MobileNetworkOperator value) {
        this.mno = value;
    }

    /**
     * Gets the value of the newPin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewPin() {
        return newPin;
    }

    /**
     * Sets the value of the newPin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewPin(String value) {
        this.newPin = value;
    }

    /**
     * Gets the value of the oldPin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldPin() {
        return oldPin;
    }

    /**
     * Sets the value of the oldPin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldPin(String value) {
        this.oldPin = value;
    }

    /**
     * Gets the value of the paymentRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentRef() {
        return paymentRef;
    }

    /**
     * Sets the value of the paymentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentRef(String value) {
        this.paymentRef = value;
    }

    /**
     * Gets the value of the refCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefCode() {
        return refCode;
    }

    /**
     * Sets the value of the refCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefCode(String value) {
        this.refCode = value;
    }

    /**
     * Gets the value of the secretCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecretCode() {
        return secretCode;
    }

    /**
     * Sets the value of the secretCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecretCode(String value) {
        this.secretCode = value;
    }

    /**
     * Gets the value of the sourceBankAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceBankAccount() {
        return sourceBankAccount;
    }

    /**
     * Sets the value of the sourceBankAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceBankAccount(String value) {
        this.sourceBankAccount = value;
    }

    /**
     * Gets the value of the sourceBankId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceBankId() {
        return sourceBankId;
    }

    /**
     * Sets the value of the sourceBankId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceBankId(String value) {
        this.sourceBankId = value;
    }

    /**
     * Gets the value of the sourceMobileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceMobileNumber() {
        return sourceMobileNumber;
    }

    /**
     * Sets the value of the sourceMobileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceMobileNumber(String value) {
        this.sourceMobileNumber = value;
    }

    /**
     * Gets the value of the targetBankAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetBankAccount() {
        return targetBankAccount;
    }

    /**
     * Sets the value of the targetBankAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetBankAccount(String value) {
        this.targetBankAccount = value;
    }

    /**
     * Gets the value of the targetBankId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetBankId() {
        return targetBankId;
    }

    /**
     * Sets the value of the targetBankId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetBankId(String value) {
        this.targetBankId = value;
    }

    /**
     * Gets the value of the targetMobileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetMobileNumber() {
        return targetMobileNumber;
    }

    /**
     * Sets the value of the targetMobileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetMobileNumber(String value) {
        this.targetMobileNumber = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link MobileWebTransactionType }
     *     
     */
    public MobileWebTransactionType getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MobileWebTransactionType }
     *     
     */
    public void setTransactionType(MobileWebTransactionType value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the utilityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtilityName() {
        return utilityName;
    }

    /**
     * Sets the value of the utilityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtilityName(String value) {
        this.utilityName = value;
    }

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

}
