//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://services.web.ussd.esolutions.co.zw/")
package zw.co.esolutions.ussd.web.services;
