//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.limitservices.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "LimitService", targetNamespace = "http://service.limitservices.ewallet.esolutions.co.zw/", wsdlLocation = "http://localhost:9081/LimitServices/LimitService/LimitService.wsdl")
public class LimitService_Service
    extends Service
{

    private final static URL LIMITSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9081/LimitServices/LimitService/LimitService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        LIMITSERVICE_WSDL_LOCATION = url;
    }

    public LimitService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LimitService_Service() {
        super(LIMITSERVICE_WSDL_LOCATION, new QName("http://service.limitservices.ewallet.esolutions.co.zw/", "LimitService"));
    }

    /**
     * 
     * @return
     *     returns LimitService
     */
    @WebEndpoint(name = "LimitServiceSOAP")
    public LimitService getLimitServiceSOAP() {
        return (LimitService)super.getPort(new QName("http://service.limitservices.ewallet.esolutions.co.zw/", "LimitServiceSOAP"), LimitService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LimitService
     */
    @WebEndpoint(name = "LimitServiceSOAP")
    public LimitService getLimitServiceSOAP(WebServiceFeature... features) {
        return (LimitService)super.getPort(new QName("http://service.limitservices.ewallet.esolutions.co.zw/", "LimitServiceSOAP"), LimitService.class, features);
    }

}
