//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.econet.econetvas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillPaymentReversalResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillPaymentReversalResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="billReversalRequest" type="{http://econetvas.econet.co.zw/}BillPaymentReversalRequest"/>
 *         &lt;element name="responseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="narrative" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillPaymentReversalResponse", namespace = "http://econetvas.econet.co.zw/", propOrder = {
    "billReversalRequest",
    "responseCode",
    "narrative"
})
public class BillPaymentReversalResponse {

    @XmlElement(required = true)
    protected BillPaymentReversalRequest billReversalRequest;
    @XmlElement(required = true)
    protected String responseCode;
    @XmlElement(required = true)
    protected String narrative;

    /**
     * Gets the value of the billReversalRequest property.
     * 
     * @return
     *     possible object is
     *     {@link BillPaymentReversalRequest }
     *     
     */
    public BillPaymentReversalRequest getBillReversalRequest() {
        return billReversalRequest;
    }

    /**
     * Sets the value of the billReversalRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillPaymentReversalRequest }
     *     
     */
    public void setBillReversalRequest(BillPaymentReversalRequest value) {
        this.billReversalRequest = value;
    }

    /**
     * Gets the value of the responseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCode(String value) {
        this.responseCode = value;
    }

    /**
     * Gets the value of the narrative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNarrative() {
        return narrative;
    }

    /**
     * Sets the value of the narrative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNarrative(String value) {
        this.narrative = value;
    }

}
