//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.econet.econetvas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for creditSubscriberResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="creditSubscriberResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="creditSubcriberResponse" type="{http://econetvas.econet.co.zw/}CreditResponse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "creditSubscriberResponse", namespace = "http://econetvas.econet.co.zw/", propOrder = {
    "creditSubcriberResponse"
})
public class CreditSubscriberResponse {

    protected CreditResponse creditSubcriberResponse;

    /**
     * Gets the value of the creditSubcriberResponse property.
     * 
     * @return
     *     possible object is
     *     {@link CreditResponse }
     *     
     */
    public CreditResponse getCreditSubcriberResponse() {
        return creditSubcriberResponse;
    }

    /**
     * Sets the value of the creditSubcriberResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditResponse }
     *     
     */
    public void setCreditSubcriberResponse(CreditResponse value) {
        this.creditSubcriberResponse = value;
    }

}
