//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.econet.econetvas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DebitResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DebitResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="debitReq" type="{http://econetvas.econet.co.zw/}DebitRequest"/>
 *         &lt;element name="responseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="narrative" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="initialBalance" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="finalBalance" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DebitResponse", namespace = "http://econetvas.econet.co.zw/", propOrder = {
    "debitReq",
    "responseCode",
    "narrative",
    "initialBalance",
    "finalBalance"
})
public class DebitResponse {

    @XmlElement(required = true)
    protected DebitRequest debitReq;
    @XmlElement(required = true)
    protected String responseCode;
    @XmlElement(required = true)
    protected String narrative;
    protected double initialBalance;
    protected double finalBalance;

    /**
     * Gets the value of the debitReq property.
     * 
     * @return
     *     possible object is
     *     {@link DebitRequest }
     *     
     */
    public DebitRequest getDebitReq() {
        return debitReq;
    }

    /**
     * Sets the value of the debitReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link DebitRequest }
     *     
     */
    public void setDebitReq(DebitRequest value) {
        this.debitReq = value;
    }

    /**
     * Gets the value of the responseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCode(String value) {
        this.responseCode = value;
    }

    /**
     * Gets the value of the narrative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNarrative() {
        return narrative;
    }

    /**
     * Sets the value of the narrative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNarrative(String value) {
        this.narrative = value;
    }

    /**
     * Gets the value of the initialBalance property.
     * 
     */
    public double getInitialBalance() {
        return initialBalance;
    }

    /**
     * Sets the value of the initialBalance property.
     * 
     */
    public void setInitialBalance(double value) {
        this.initialBalance = value;
    }

    /**
     * Gets the value of the finalBalance property.
     * 
     */
    public double getFinalBalance() {
        return finalBalance;
    }

    /**
     * Sets the value of the finalBalance property.
     * 
     */
    public void setFinalBalance(double value) {
        this.finalBalance = value;
    }

}
