//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.econet.econetvas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "econetvas", targetNamespace = "http://econetvas.econet.co.zw/", wsdlLocation = "file:/META-INF/wsdl/Econetvas.wsdl")
public class Econetvas_Service
    extends Service
{

    private final static URL ECONETVAS_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/META-INF/wsdl/Econetvas.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ECONETVAS_WSDL_LOCATION = url;
    }

    public Econetvas_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Econetvas_Service() {
        super(ECONETVAS_WSDL_LOCATION, new QName("http://econetvas.econet.co.zw/", "econetvas"));
    }

    /**
     * 
     * @return
     *     returns Econetvas
     */
    @WebEndpoint(name = "econetvasSOAP")
    public Econetvas getEconetvasSOAP() {
        return (Econetvas)super.getPort(new QName("http://econetvas.econet.co.zw/", "econetvasSOAP"), Econetvas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Econetvas
     */
    @WebEndpoint(name = "econetvasSOAP")
    public Econetvas getEconetvasSOAP(WebServiceFeature... features) {
        return (Econetvas)super.getPort(new QName("http://econetvas.econet.co.zw/", "econetvasSOAP"), Econetvas.class, features);
    }

}
