//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.tariffservices.service;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for agentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="agentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AGENT"/>
 *     &lt;enumeration value="BANK_BRANCH"/>
 *     &lt;enumeration value="SUPER_AGENT"/>
 *     &lt;enumeration value="SUB_AGENT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "agentType", namespace = "http://service.tariffservices.ewallet.esolutions.co.zw/")
@XmlEnum
public enum AgentType {

    AGENT,
    BANK_BRANCH,
    SUPER_AGENT,
    SUB_AGENT;

    public String value() {
        return name();
    }

    public static AgentType fromValue(String v) {
        return valueOf(v);
    }

}
