CREATE TABLE USSD.UserAccount (id VARCHAR(254) NOT NULL, accountNumber VARCHAR(30), accountType VARCHAR(25), version INTEGER, PRIMARY KEY (id));
CREATE TABLE USSD.UserInput (id VARCHAR(254) NOT NULL, inputKey VARCHAR(254), inputValue VARCHAR(254), version INTEGER, PRIMARY KEY (id));
CREATE TABLE USSD.USSDSession (sessionId VARCHAR(254) NOT NULL, accountType SMALLINT, authenticated SMALLINT, bankId VARCHAR(40), customerId VARCHAR(60), dateCreated TIMESTAMP, hasBankAccounts SMALLINT, hasEwalletAccounts SMALLINT, level INTEGER, mobileNumber VARCHAR(15), optionsMenu VARCHAR(350), serviceName VARCHAR(60), status VARCHAR(30), transactionTime TIMESTAMP, ussdRequestCode VARCHAR(60), version INTEGER, PRIMARY KEY (sessionId));
CREATE TABLE USSD.USSDSession_UserAccount (USSDSESSION_SESSIONID VARCHAR(254), USERACCOUNTS_ID VARCHAR(254));
CREATE TABLE USSD.USSDSession_UserInput (USSDSESSION_SESSIONID VARCHAR(254), USERINPUT_ID VARCHAR(254));
ALTER TABLE USSD.USSDSession_UserAccount ADD FOREIGN KEY (USSDSESSION_SESSIONID) REFERENCES USSD.USSDSession (sessionId);
ALTER TABLE USSD.USSDSession_UserAccount ADD FOREIGN KEY (USERACCOUNTS_ID) REFERENCES USSD.UserAccount (id);
ALTER TABLE USSD.USSDSession_UserInput ADD FOREIGN KEY (USSDSESSION_SESSIONID) REFERENCES USSD.USSDSession (sessionId);
ALTER TABLE USSD.USSDSession_UserInput ADD FOREIGN KEY (USERINPUT_ID) REFERENCES USSD.UserInput (id);
