//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.econet.dedicatedacc.impl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the zw.co.econet.dedicatedacc.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UpdateDA_QNAME = new QName("http://impl.dedicatedacc.econet.co.zw/", "updateDA");
    private final static QName _GetPlatFormInfo_QNAME = new QName("http://impl.dedicatedacc.econet.co.zw/", "getPlatFormInfo");
    private final static QName _UpdateDAResponse_QNAME = new QName("http://impl.dedicatedacc.econet.co.zw/", "updateDAResponse");
    private final static QName _VoidUpdateDA_QNAME = new QName("http://impl.dedicatedacc.econet.co.zw/", "voidUpdateDA");
    private final static QName _VoidUpdateDAResponse_QNAME = new QName("http://impl.dedicatedacc.econet.co.zw/", "voidUpdateDAResponse");
    private final static QName _GetDedicatedAccountBalance_QNAME = new QName("http://impl.dedicatedacc.econet.co.zw/", "getDedicatedAccountBalance");
    private final static QName _GetPlatFormInfoResponse_QNAME = new QName("http://impl.dedicatedacc.econet.co.zw/", "getPlatFormInfoResponse");
    private final static QName _ReverseUpdateDA_QNAME = new QName("http://impl.dedicatedacc.econet.co.zw/", "reverseUpdateDA");
    private final static QName _GetDedicatedAccountBalanceResponse_QNAME = new QName("http://impl.dedicatedacc.econet.co.zw/", "getDedicatedAccountBalanceResponse");
    private final static QName _ReverseUpdateDAResponse_QNAME = new QName("http://impl.dedicatedacc.econet.co.zw/", "reverseUpdateDAResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: zw.co.econet.dedicatedacc.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateDA }
     * 
     */
    public UpdateDA createUpdateDA() {
        return new UpdateDA();
    }

    /**
     * Create an instance of {@link GetDedicatedAccountBalanceResponse }
     * 
     */
    public GetDedicatedAccountBalanceResponse createGetDedicatedAccountBalanceResponse() {
        return new GetDedicatedAccountBalanceResponse();
    }

    /**
     * Create an instance of {@link ReverseUpdateDA }
     * 
     */
    public ReverseUpdateDA createReverseUpdateDA() {
        return new ReverseUpdateDA();
    }

    /**
     * Create an instance of {@link QueryDABalance }
     * 
     */
    public QueryDABalance createQueryDABalance() {
        return new QueryDABalance();
    }

    /**
     * Create an instance of {@link ResultWrapper }
     * 
     */
    public ResultWrapper createResultWrapper() {
        return new ResultWrapper();
    }

    /**
     * Create an instance of {@link GetPlatFormInfo }
     * 
     */
    public GetPlatFormInfo createGetPlatFormInfo() {
        return new GetPlatFormInfo();
    }

    /**
     * Create an instance of {@link GetPlatFormInfoResponse }
     * 
     */
    public GetPlatFormInfoResponse createGetPlatFormInfoResponse() {
        return new GetPlatFormInfoResponse();
    }

    /**
     * Create an instance of {@link UpdateDARequest }
     * 
     */
    public UpdateDARequest createUpdateDARequest() {
        return new UpdateDARequest();
    }

    /**
     * Create an instance of {@link UpdateDAResponse }
     * 
     */
    public UpdateDAResponse createUpdateDAResponse() {
        return new UpdateDAResponse();
    }

    /**
     * Create an instance of {@link PlatformInfo }
     * 
     */
    public PlatformInfo createPlatformInfo() {
        return new PlatformInfo();
    }

    /**
     * Create an instance of {@link GetDedicatedAccountBalance }
     * 
     */
    public GetDedicatedAccountBalance createGetDedicatedAccountBalance() {
        return new GetDedicatedAccountBalance();
    }

    /**
     * Create an instance of {@link VoidUpdateDA }
     * 
     */
    public VoidUpdateDA createVoidUpdateDA() {
        return new VoidUpdateDA();
    }

    /**
     * Create an instance of {@link ReverseUpdateDAResponse }
     * 
     */
    public ReverseUpdateDAResponse createReverseUpdateDAResponse() {
        return new ReverseUpdateDAResponse();
    }

    /**
     * Create an instance of {@link VoidUpdateDAResponse }
     * 
     */
    public VoidUpdateDAResponse createVoidUpdateDAResponse() {
        return new VoidUpdateDAResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateDA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.dedicatedacc.econet.co.zw/", name = "updateDA")
    public JAXBElement<UpdateDA> createUpdateDA(UpdateDA value) {
        return new JAXBElement<UpdateDA>(_UpdateDA_QNAME, UpdateDA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPlatFormInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.dedicatedacc.econet.co.zw/", name = "getPlatFormInfo")
    public JAXBElement<GetPlatFormInfo> createGetPlatFormInfo(GetPlatFormInfo value) {
        return new JAXBElement<GetPlatFormInfo>(_GetPlatFormInfo_QNAME, GetPlatFormInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateDAResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.dedicatedacc.econet.co.zw/", name = "updateDAResponse")
    public JAXBElement<UpdateDAResponse> createUpdateDAResponse(UpdateDAResponse value) {
        return new JAXBElement<UpdateDAResponse>(_UpdateDAResponse_QNAME, UpdateDAResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VoidUpdateDA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.dedicatedacc.econet.co.zw/", name = "voidUpdateDA")
    public JAXBElement<VoidUpdateDA> createVoidUpdateDA(VoidUpdateDA value) {
        return new JAXBElement<VoidUpdateDA>(_VoidUpdateDA_QNAME, VoidUpdateDA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VoidUpdateDAResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.dedicatedacc.econet.co.zw/", name = "voidUpdateDAResponse")
    public JAXBElement<VoidUpdateDAResponse> createVoidUpdateDAResponse(VoidUpdateDAResponse value) {
        return new JAXBElement<VoidUpdateDAResponse>(_VoidUpdateDAResponse_QNAME, VoidUpdateDAResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDedicatedAccountBalance }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.dedicatedacc.econet.co.zw/", name = "getDedicatedAccountBalance")
    public JAXBElement<GetDedicatedAccountBalance> createGetDedicatedAccountBalance(GetDedicatedAccountBalance value) {
        return new JAXBElement<GetDedicatedAccountBalance>(_GetDedicatedAccountBalance_QNAME, GetDedicatedAccountBalance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPlatFormInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.dedicatedacc.econet.co.zw/", name = "getPlatFormInfoResponse")
    public JAXBElement<GetPlatFormInfoResponse> createGetPlatFormInfoResponse(GetPlatFormInfoResponse value) {
        return new JAXBElement<GetPlatFormInfoResponse>(_GetPlatFormInfoResponse_QNAME, GetPlatFormInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReverseUpdateDA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.dedicatedacc.econet.co.zw/", name = "reverseUpdateDA")
    public JAXBElement<ReverseUpdateDA> createReverseUpdateDA(ReverseUpdateDA value) {
        return new JAXBElement<ReverseUpdateDA>(_ReverseUpdateDA_QNAME, ReverseUpdateDA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDedicatedAccountBalanceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.dedicatedacc.econet.co.zw/", name = "getDedicatedAccountBalanceResponse")
    public JAXBElement<GetDedicatedAccountBalanceResponse> createGetDedicatedAccountBalanceResponse(GetDedicatedAccountBalanceResponse value) {
        return new JAXBElement<GetDedicatedAccountBalanceResponse>(_GetDedicatedAccountBalanceResponse_QNAME, GetDedicatedAccountBalanceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReverseUpdateDAResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://impl.dedicatedacc.econet.co.zw/", name = "reverseUpdateDAResponse")
    public JAXBElement<ReverseUpdateDAResponse> createReverseUpdateDAResponse(ReverseUpdateDAResponse value) {
        return new JAXBElement<ReverseUpdateDAResponse>(_ReverseUpdateDAResponse_QNAME, ReverseUpdateDAResponse.class, null, value);
    }

}
