//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4)
//


package zw.co.esolutions.ewallet.process;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for deleteProcessTransactionsByDayEnd complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deleteProcessTransactionsByDayEnd">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dayEnd" type="{http://process.ewallet.esolutions.co.zw/}dayEnd" minOccurs="0"/>
 *         &lt;element name="arg1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteProcessTransactionsByDayEnd", propOrder = {
    "dayEnd",
    "arg1"
})
public class DeleteProcessTransactionsByDayEnd {

    protected DayEnd dayEnd;
    protected String arg1;

    /**
     * Gets the value of the dayEnd property.
     * 
     * @return
     *     possible object is
     *     {@link DayEnd }
     *     
     */
    public DayEnd getDayEnd() {
        return dayEnd;
    }

    /**
     * Sets the value of the dayEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayEnd }
     *     
     */
    public void setDayEnd(DayEnd value) {
        this.dayEnd = value;
    }

    /**
     * Gets the value of the arg1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArg1() {
        return arg1;
    }

    /**
     * Sets the value of the arg1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArg1(String value) {
        this.arg1 = value;
    }

}
