//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4)
//


package zw.co.esolutions.ewallet.process;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transactionLocationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="transactionLocationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BANK_BRANCH"/>
 *     &lt;enumeration value="AGENT"/>
 *     &lt;enumeration value="ATM"/>
 *     &lt;enumeration value="SMS"/>
 *     &lt;enumeration value="USSD"/>
 *     &lt;enumeration value="BULK"/>
 *     &lt;enumeration value="MOBILE_WEB"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "transactionLocationType")
@XmlEnum
public enum TransactionLocationType {

    BANK_BRANCH,
    AGENT,
    ATM,
    SMS,
    USSD,
    BULK,
    MOBILE_WEB;

    public String value() {
        return name();
    }

    public static TransactionLocationType fromValue(String v) {
        return valueOf(v);
    }

}
