//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-05/12/2011 11:54 AM(foreman)-)
//


package zw.co.esolutions.mcommerce.refgen.service;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ReferenceGeneratorService", targetNamespace = "http://service.refgen.mcommerce.esolutions.co.zw/", wsdlLocation = "META-INF/wsdl/ReferenceGeneratorService.wsdl")
public class ReferenceGeneratorService_Service
    extends Service
{

    private final static URL REFERENCEGENERATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException REFERENCEGENERATORSERVICE_EXCEPTION;
    private final static QName REFERENCEGENERATORSERVICE_QNAME = new QName("http://service.refgen.mcommerce.esolutions.co.zw/", "ReferenceGeneratorService");

    static {
            REFERENCEGENERATORSERVICE_WSDL_LOCATION = zw.co.esolutions.mcommerce.refgen.service.ReferenceGeneratorService_Service.class.getResource("/META-INF/wsdl/ReferenceGeneratorService.wsdl");
        WebServiceException e = null;
        if (REFERENCEGENERATORSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/ReferenceGeneratorService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        REFERENCEGENERATORSERVICE_EXCEPTION = e;
    }

    public ReferenceGeneratorService_Service() {
        super(__getWsdlLocation(), REFERENCEGENERATORSERVICE_QNAME);
    }

    public ReferenceGeneratorService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), REFERENCEGENERATORSERVICE_QNAME, features);
    }

    public ReferenceGeneratorService_Service(URL wsdlLocation) {
        super(wsdlLocation, REFERENCEGENERATORSERVICE_QNAME);
    }

    public ReferenceGeneratorService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REFERENCEGENERATORSERVICE_QNAME, features);
    }

    public ReferenceGeneratorService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReferenceGeneratorService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReferenceGeneratorService
     */
    @WebEndpoint(name = "ReferenceGeneratorServiceSOAP")
    public ReferenceGeneratorService getReferenceGeneratorServiceSOAP() {
        return super.getPort(new QName("http://service.refgen.mcommerce.esolutions.co.zw/", "ReferenceGeneratorServiceSOAP"), ReferenceGeneratorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReferenceGeneratorService
     */
    @WebEndpoint(name = "ReferenceGeneratorServiceSOAP")
    public ReferenceGeneratorService getReferenceGeneratorServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.refgen.mcommerce.esolutions.co.zw/", "ReferenceGeneratorServiceSOAP"), ReferenceGeneratorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REFERENCEGENERATORSERVICE_EXCEPTION!= null) {
            throw REFERENCEGENERATORSERVICE_EXCEPTION;
        }
        return REFERENCEGENERATORSERVICE_WSDL_LOCATION;
    }

}
