//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.bankservices.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "BankService", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param userName
     * @param bank
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.Bank
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createBank", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.CreateBank")
    @ResponseWrapper(localName = "createBankResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.CreateBankResponse")
    public Bank createBank(
        @WebParam(name = "bank", targetNamespace = "")
        Bank bank,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param userName
     * @param bank
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteBank", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.DeleteBank")
    @ResponseWrapper(localName = "deleteBankResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.DeleteBankResponse")
    public String deleteBank(
        @WebParam(name = "bank", targetNamespace = "")
        Bank bank,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param userName
     * @param bank
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.Bank
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "approveBank", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.ApproveBank")
    @ResponseWrapper(localName = "approveBankResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.ApproveBankResponse")
    public Bank approveBank(
        @WebParam(name = "bank", targetNamespace = "")
        Bank bank,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param userName
     * @param bank
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.Bank
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editBank", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.EditBank")
    @ResponseWrapper(localName = "editBankResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.EditBankResponse")
    public Bank editBank(
        @WebParam(name = "bank", targetNamespace = "")
        Bank bank,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.Bank
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findBankById", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.FindBankById")
    @ResponseWrapper(localName = "findBankByIdResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.FindBankByIdResponse")
    public Bank findBankById(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @param code
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.Bank
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankByCode", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankByCode")
    @ResponseWrapper(localName = "getBankByCodeResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankByCodeResponse")
    public Bank getBankByCode(
        @WebParam(name = "code", targetNamespace = "")
        String code);

    /**
     * 
     * @param name
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.Bank>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankByName", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankByName")
    @ResponseWrapper(localName = "getBankByNameResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankByNameResponse")
    public List<Bank> getBankByName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.Bank>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBank", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBank")
    @ResponseWrapper(localName = "getBankResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankResponse")
    public List<Bank> getBank();

    /**
     * 
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankBranch>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankBranch", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankBranch")
    @ResponseWrapper(localName = "getBankBranchResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankBranchResponse")
    public List<BankBranch> getBankBranch();

    /**
     * 
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccount", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccount")
    @ResponseWrapper(localName = "getBankAccountResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountResponse")
    public List<BankAccount> getBankAccount();

    /**
     * 
     * @param userName
     * @param bankBranch
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankBranch
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createBankBranch", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.CreateBankBranch")
    @ResponseWrapper(localName = "createBankBranchResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.CreateBankBranchResponse")
    public BankBranch createBankBranch(
        @WebParam(name = "bankBranch", targetNamespace = "")
        BankBranch bankBranch,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param userName
     * @param bankBranch
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteBankBranch", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.DeleteBankBranch")
    @ResponseWrapper(localName = "deleteBankBranchResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.DeleteBankBranchResponse")
    public String deleteBankBranch(
        @WebParam(name = "bankBranch", targetNamespace = "")
        BankBranch bankBranch,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param userName
     * @param bankBranch
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankBranch
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "approveBankBranch", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.ApproveBankBranch")
    @ResponseWrapper(localName = "approveBankBranchResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.ApproveBankBranchResponse")
    public BankBranch approveBankBranch(
        @WebParam(name = "bankBranch", targetNamespace = "")
        BankBranch bankBranch,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param userName
     * @param bankBranch
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankBranch
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rejectBankBranch", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.RejectBankBranch")
    @ResponseWrapper(localName = "rejectBankBranchResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.RejectBankBranchResponse")
    public BankBranch rejectBankBranch(
        @WebParam(name = "bankBranch", targetNamespace = "")
        BankBranch bankBranch,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param userName
     * @param bankBranch
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankBranch
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editBankBranch", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.EditBankBranch")
    @ResponseWrapper(localName = "editBankBranchResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.EditBankBranchResponse")
    public BankBranch editBankBranch(
        @WebParam(name = "bankBranch", targetNamespace = "")
        BankBranch bankBranch,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankBranch
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findBankBranchById", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.FindBankBranchById")
    @ResponseWrapper(localName = "findBankBranchByIdResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.FindBankBranchByIdResponse")
    public BankBranch findBankBranchById(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @param code
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankBranch
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankBranchByCode", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankBranchByCode")
    @ResponseWrapper(localName = "getBankBranchByCodeResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankBranchByCodeResponse")
    public BankBranch getBankBranchByCode(
        @WebParam(name = "code", targetNamespace = "")
        String code);

    /**
     * 
     * @param name
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankBranch>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankBranchByName", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankBranchByName")
    @ResponseWrapper(localName = "getBankBranchByNameResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankBranchByNameResponse")
    public List<BankBranch> getBankBranchByName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param status
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankBranch>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankBranchByStatus", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankBranchByStatus")
    @ResponseWrapper(localName = "getBankBranchByStatusResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankBranchByStatusResponse")
    public List<BankBranch> getBankBranchByStatus(
        @WebParam(name = "status", targetNamespace = "")
        BankBranchStatus status);

    /**
     * 
     * @param bankId
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankBranch>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankBranchByBank", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankBranchByBank")
    @ResponseWrapper(localName = "getBankBranchByBankResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankBranchByBankResponse")
    public List<BankBranch> getBankBranchByBank(
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param bankAccount
     * @param userName
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankAccount
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createBankAccount", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.CreateBankAccount")
    @ResponseWrapper(localName = "createBankAccountResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.CreateBankAccountResponse")
    public BankAccount createBankAccount(
        @WebParam(name = "bankAccount", targetNamespace = "")
        BankAccount bankAccount,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param bankAccount
     * @param userName
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankAccount
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteBankAccount", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.DeleteBankAccount")
    @ResponseWrapper(localName = "deleteBankAccountResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.DeleteBankAccountResponse")
    public BankAccount deleteBankAccount(
        @WebParam(name = "bankAccount", targetNamespace = "")
        BankAccount bankAccount,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param bankAccount
     * @param userName
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankAccount
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "approveBankAccount", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.ApproveBankAccount")
    @ResponseWrapper(localName = "approveBankAccountResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.ApproveBankAccountResponse")
    public BankAccount approveBankAccount(
        @WebParam(name = "bankAccount", targetNamespace = "")
        BankAccount bankAccount,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param bankAccount
     * @param userName
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankAccount
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rejectBankAccount", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.RejectBankAccount")
    @ResponseWrapper(localName = "rejectBankAccountResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.RejectBankAccountResponse")
    public BankAccount rejectBankAccount(
        @WebParam(name = "bankAccount", targetNamespace = "")
        BankAccount bankAccount,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param bankAccount
     * @param userName
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankAccount
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editBankAccount", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.EditBankAccount")
    @ResponseWrapper(localName = "editBankAccountResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.EditBankAccountResponse")
    public BankAccount editBankAccount(
        @WebParam(name = "bankAccount", targetNamespace = "")
        BankAccount bankAccount,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankAccount
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findBankAccountById", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.FindBankAccountById")
    @ResponseWrapper(localName = "findBankAccountByIdResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.FindBankAccountByIdResponse")
    public BankAccount findBankAccountById(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @param accountHolderId
     * @param ownerType
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountByAccountHolderIdAndOwnerType", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByAccountHolderIdAndOwnerType")
    @ResponseWrapper(localName = "getBankAccountByAccountHolderIdAndOwnerTypeResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByAccountHolderIdAndOwnerTypeResponse")
    public List<BankAccount> getBankAccountByAccountHolderIdAndOwnerType(
        @WebParam(name = "accountHolderId", targetNamespace = "")
        String accountHolderId,
        @WebParam(name = "ownerType", targetNamespace = "")
        OwnerType ownerType);

    /**
     * 
     * @param accountNumber
     * @param ownerType
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankAccount
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountByAccountNumberAndOwnerType", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByAccountNumberAndOwnerType")
    @ResponseWrapper(localName = "getBankAccountByAccountNumberAndOwnerTypeResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByAccountNumberAndOwnerTypeResponse")
    public BankAccount getBankAccountByAccountNumberAndOwnerType(
        @WebParam(name = "accountNumber", targetNamespace = "")
        String accountNumber,
        @WebParam(name = "ownerType", targetNamespace = "")
        OwnerType ownerType);

    /**
     * 
     * @param bankAccountNumber
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountsByAccountNumber", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountsByAccountNumber")
    @ResponseWrapper(localName = "getBankAccountsByAccountNumberResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountsByAccountNumberResponse")
    public List<BankAccount> getBankAccountsByAccountNumber(
        @WebParam(name = "bankAccountNumber", targetNamespace = "")
        String bankAccountNumber);

    /**
     * 
     * @param status
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountByStatus", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByStatus")
    @ResponseWrapper(localName = "getBankAccountByStatusResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByStatusResponse")
    public List<BankAccount> getBankAccountByStatus(
        @WebParam(name = "status", targetNamespace = "")
        BankAccountStatus status);

    /**
     * 
     * @param status
     * @param ownerType
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountByStatusAndOwnerType", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByStatusAndOwnerType")
    @ResponseWrapper(localName = "getBankAccountByStatusAndOwnerTypeResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByStatusAndOwnerTypeResponse")
    public List<BankAccount> getBankAccountByStatusAndOwnerType(
        @WebParam(name = "status", targetNamespace = "")
        BankAccountStatus status,
        @WebParam(name = "ownerType", targetNamespace = "")
        OwnerType ownerType);

    /**
     * 
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountsAwaitingApproval", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountsAwaitingApproval")
    @ResponseWrapper(localName = "getBankAccountsAwaitingApprovalResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountsAwaitingApprovalResponse")
    public List<BankAccount> getBankAccountsAwaitingApproval();

    /**
     * 
     * @param type
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountByType", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByType")
    @ResponseWrapper(localName = "getBankAccountByTypeResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByTypeResponse")
    public List<BankAccount> getBankAccountByType(
        @WebParam(name = "type", targetNamespace = "")
        BankAccountType type);

    /**
     * 
     * @param level
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountByLevel", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByLevel")
    @ResponseWrapper(localName = "getBankAccountByLevelResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByLevelResponse")
    public List<BankAccount> getBankAccountByLevel(
        @WebParam(name = "level", targetNamespace = "")
        String level);

    /**
     * 
     * @param branchId
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountByBranch", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByBranch")
    @ResponseWrapper(localName = "getBankAccountByBranchResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByBranchResponse")
    public List<BankAccount> getBankAccountByBranch(
        @WebParam(name = "branchId", targetNamespace = "")
        String branchId);

    /**
     * 
     * @param bankId
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountByBank", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByBank")
    @ResponseWrapper(localName = "getBankAccountByBankResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByBankResponse")
    public List<BankAccount> getBankAccountByBank(
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param accountHolderId
     * @param accountNumber
     * @param type
     * @param ownerType
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankAccount
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountByAccountHolderAndTypeAndOwnerType", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByAccountHolderAndTypeAndOwnerType")
    @ResponseWrapper(localName = "getBankAccountByAccountHolderAndTypeAndOwnerTypeResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByAccountHolderAndTypeAndOwnerTypeResponse")
    public BankAccount getBankAccountByAccountHolderAndTypeAndOwnerType(
        @WebParam(name = "accountHolderId", targetNamespace = "")
        String accountHolderId,
        @WebParam(name = "type", targetNamespace = "")
        BankAccountType type,
        @WebParam(name = "ownerType", targetNamespace = "")
        OwnerType ownerType,
        @WebParam(name = "accountNumber", targetNamespace = "")
        String accountNumber)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountByLevelAndStatus", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByLevelAndStatus")
    @ResponseWrapper(localName = "getBankAccountByLevelAndStatusResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountByLevelAndStatusResponse")
    public List<BankAccount> getBankAccountByLevelAndStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        BankAccountLevel arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BankAccountStatus arg1);

    /**
     * 
     * @param accountHolderId
     * @param isPrimaryAccount
     * @param ownerType
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankAccount
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrimaryAccountByAccountHolderIdAndOwnerType", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetPrimaryAccountByAccountHolderIdAndOwnerType")
    @ResponseWrapper(localName = "getPrimaryAccountByAccountHolderIdAndOwnerTypeResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetPrimaryAccountByAccountHolderIdAndOwnerTypeResponse")
    public BankAccount getPrimaryAccountByAccountHolderIdAndOwnerType(
        @WebParam(name = "isPrimaryAccount", targetNamespace = "")
        boolean isPrimaryAccount,
        @WebParam(name = "accountHolderId", targetNamespace = "")
        String accountHolderId,
        @WebParam(name = "ownerType", targetNamespace = "")
        OwnerType ownerType);

    /**
     * 
     * @param status
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.Bank>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankByStatus", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankByStatus")
    @ResponseWrapper(localName = "getBankByStatusResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankByStatusResponse")
    public List<Bank> getBankByStatus(
        @WebParam(name = "status", targetNamespace = "")
        BankStatus status);

    /**
     * 
     * @param userName
     * @param ownerId
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deRegisterBankAccountsByOwnerId", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.DeRegisterBankAccountsByOwnerId")
    @ResponseWrapper(localName = "deRegisterBankAccountsByOwnerIdResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.DeRegisterBankAccountsByOwnerIdResponse")
    public List<BankAccount> deRegisterBankAccountsByOwnerId(
        @WebParam(name = "ownerId", targetNamespace = "")
        String ownerId,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param status
     * @param accountHolderId
     * @param ownerType
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountsByAccountHolderIdAndOwnerTypeAndStatus", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountsByAccountHolderIdAndOwnerTypeAndStatus")
    @ResponseWrapper(localName = "getBankAccountsByAccountHolderIdAndOwnerTypeAndStatusResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountsByAccountHolderIdAndOwnerTypeAndStatusResponse")
    public List<BankAccount> getBankAccountsByAccountHolderIdAndOwnerTypeAndStatus(
        @WebParam(name = "accountHolderId", targetNamespace = "")
        String accountHolderId,
        @WebParam(name = "ownerType", targetNamespace = "")
        OwnerType ownerType,
        @WebParam(name = "status", targetNamespace = "")
        BankAccountStatus status);

    /**
     * 
     * @param bankAAccountType
     * @param status
     * @param accountHolderId
     * @param ownerType
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountsByAccountHolderIdAndOwnerTypeAndStatusAndBankAccountType", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountsByAccountHolderIdAndOwnerTypeAndStatusAndBankAccountType")
    @ResponseWrapper(localName = "getBankAccountsByAccountHolderIdAndOwnerTypeAndStatusAndBankAccountTypeResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountsByAccountHolderIdAndOwnerTypeAndStatusAndBankAccountTypeResponse")
    public List<BankAccount> getBankAccountsByAccountHolderIdAndOwnerTypeAndStatusAndBankAccountType(
        @WebParam(name = "accountHolderId", targetNamespace = "")
        String accountHolderId,
        @WebParam(name = "ownerType", targetNamespace = "")
        OwnerType ownerType,
        @WebParam(name = "status", targetNamespace = "")
        BankAccountStatus status,
        @WebParam(name = "bankAAccountType", targetNamespace = "")
        BankAccountType bankAAccountType);

    /**
     * 
     * @param startIndex
     * @param maxResults
     * @param status
     * @param accountNumber
     * @param bankId
     * @param accountName
     * @param accType
     * @param branchId
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.BankAccount>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountsByMinAttributes", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountsByMinAttributes")
    @ResponseWrapper(localName = "getBankAccountsByMinAttributesResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountsByMinAttributesResponse")
    public List<BankAccount> getBankAccountsByMinAttributes(
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId,
        @WebParam(name = "branchId", targetNamespace = "")
        String branchId,
        @WebParam(name = "accType", targetNamespace = "")
        BankAccountType accType,
        @WebParam(name = "accountNumber", targetNamespace = "")
        String accountNumber,
        @WebParam(name = "accountName", targetNamespace = "")
        String accountName,
        @WebParam(name = "status", targetNamespace = "")
        BankAccountStatus status,
        @WebParam(name = "startIndex", targetNamespace = "")
        int startIndex,
        @WebParam(name = "maxResults", targetNamespace = "")
        int maxResults);

    /**
     * 
     * @param accountHolderId
     * @param bankAccountType
     * @param ownerType
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankAccount
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBankAccountsByAccountHolderIdAndOwnerTypeAndBankAccountType", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountsByAccountHolderIdAndOwnerTypeAndBankAccountType")
    @ResponseWrapper(localName = "getBankAccountsByAccountHolderIdAndOwnerTypeAndBankAccountTypeResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetBankAccountsByAccountHolderIdAndOwnerTypeAndBankAccountTypeResponse")
    public BankAccount getBankAccountsByAccountHolderIdAndOwnerTypeAndBankAccountType(
        @WebParam(name = "accountHolderId", targetNamespace = "")
        String accountHolderId,
        @WebParam(name = "ownerType", targetNamespace = "")
        OwnerType ownerType,
        @WebParam(name = "bankAccountType", targetNamespace = "")
        BankAccountType bankAccountType);

    /**
     * 
     * @param bankAccount
     * @param userName
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankAccount
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deRegisterBankAccount", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.DeRegisterBankAccount")
    @ResponseWrapper(localName = "deRegisterBankAccountResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.DeRegisterBankAccountResponse")
    public BankAccount deRegisterBankAccount(
        @WebParam(name = "bankAccount", targetNamespace = "")
        BankAccount bankAccount,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param bankAccount
     * @param userName
     * @param source
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankAccount
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCustomerBankAccount", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.CreateCustomerBankAccount")
    @ResponseWrapper(localName = "createCustomerBankAccountResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.CreateCustomerBankAccountResponse")
    public BankAccount createCustomerBankAccount(
        @WebParam(name = "bankAccount", targetNamespace = "")
        BankAccount bankAccount,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "userName", targetNamespace = "")
        String userName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param accountNumber
     * @param bankId
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankAccount
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUniqueBankAccountByAccountNumberAndBankId", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetUniqueBankAccountByAccountNumberAndBankId")
    @ResponseWrapper(localName = "getUniqueBankAccountByAccountNumberAndBankIdResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetUniqueBankAccountByAccountNumberAndBankIdResponse")
    public BankAccount getUniqueBankAccountByAccountNumberAndBankId(
        @WebParam(name = "accountNumber", targetNamespace = "")
        String accountNumber,
        @WebParam(name = "bankId", targetNamespace = "")
        String bankId);

    /**
     * 
     * @param accountNumber
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.BankAccount
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUniqueBankAccountByAccountNumber", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetUniqueBankAccountByAccountNumber")
    @ResponseWrapper(localName = "getUniqueBankAccountByAccountNumberResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetUniqueBankAccountByAccountNumberResponse")
    public BankAccount getUniqueBankAccountByAccountNumber(
        @WebParam(name = "accountNumber", targetNamespace = "")
        String accountNumber);

    /**
     * 
     * @param accountBalance
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.AccountBalance
     * @throws EWalletException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccountBalance", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.CreateAccountBalance")
    @ResponseWrapper(localName = "createAccountBalanceResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.CreateAccountBalanceResponse")
    public AccountBalance createAccountBalance(
        @WebParam(name = "accountBalance", targetNamespace = "")
        AccountBalance accountBalance)
        throws EWalletException_Exception
    ;

    /**
     * 
     * @param accountBalanceId
     * @return
     *     returns java.lang.String
     * @throws EWalletException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAccountBalance", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.DeleteAccountBalance")
    @ResponseWrapper(localName = "deleteAccountBalanceResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.DeleteAccountBalanceResponse")
    public String deleteAccountBalance(
        @WebParam(name = "accountBalanceId", targetNamespace = "")
        String accountBalanceId)
        throws EWalletException_Exception
    ;

    /**
     * 
     * @param accountBalance
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.AccountBalance
     * @throws EWalletException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateAccountBalance", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.UpdateAccountBalance")
    @ResponseWrapper(localName = "updateAccountBalanceResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.UpdateAccountBalanceResponse")
    public AccountBalance updateAccountBalance(
        @WebParam(name = "accountBalance", targetNamespace = "")
        AccountBalance accountBalance)
        throws EWalletException_Exception
    ;

    /**
     * 
     * @param accountBalanceId
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.AccountBalance
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAccountBalanceById", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.FindAccountBalanceById")
    @ResponseWrapper(localName = "findAccountBalanceByIdResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.FindAccountBalanceByIdResponse")
    public AccountBalance findAccountBalanceById(
        @WebParam(name = "accountBalanceId", targetNamespace = "")
        String accountBalanceId);

    /**
     * 
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.AccountBalance>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllAccountBalances", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.FindAllAccountBalances")
    @ResponseWrapper(localName = "findAllAccountBalancesResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.FindAllAccountBalancesResponse")
    public List<AccountBalance> findAllAccountBalances();

    /**
     * 
     * @param transaction
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.Transaction
     * @throws EWalletException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTransaction", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.CreateTransaction")
    @ResponseWrapper(localName = "createTransactionResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.CreateTransactionResponse")
    public Transaction createTransaction(
        @WebParam(name = "transaction", targetNamespace = "")
        Transaction transaction)
        throws EWalletException_Exception
    ;

    /**
     * 
     * @param transactionId
     * @return
     *     returns java.lang.String
     * @throws EWalletException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteTransaction", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.DeleteTransaction")
    @ResponseWrapper(localName = "deleteTransactionResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.DeleteTransactionResponse")
    public String deleteTransaction(
        @WebParam(name = "transactionId", targetNamespace = "")
        String transactionId)
        throws EWalletException_Exception
    ;

    /**
     * 
     * @param transaction
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.Transaction
     * @throws EWalletException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateTransaction", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.UpdateTransaction")
    @ResponseWrapper(localName = "updateTransactionResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.UpdateTransactionResponse")
    public Transaction updateTransaction(
        @WebParam(name = "transaction", targetNamespace = "")
        Transaction transaction)
        throws EWalletException_Exception
    ;

    /**
     * 
     * @param transactionId
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.Transaction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findTransactionById", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.FindTransactionById")
    @ResponseWrapper(localName = "findTransactionByIdResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.FindTransactionByIdResponse")
    public Transaction findTransactionById(
        @WebParam(name = "transactionId", targetNamespace = "")
        String transactionId);

    /**
     * 
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.Transaction>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllTransactions", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.FindAllTransactions")
    @ResponseWrapper(localName = "findAllTransactionsResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.FindAllTransactionsResponse")
    public List<Transaction> findAllTransactions();

    /**
     * 
     * @param accountId
     * @param transactionDate
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.AccountBalance
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountBalanceByAccountAndDate", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetAccountBalanceByAccountAndDate")
    @ResponseWrapper(localName = "getAccountBalanceByAccountAndDateResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetAccountBalanceByAccountAndDateResponse")
    public AccountBalance getAccountBalanceByAccountAndDate(
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId,
        @WebParam(name = "transactionDate", targetNamespace = "")
        XMLGregorianCalendar transactionDate)
        throws Exception_Exception
    ;

    /**
     * 
     * @param accountId
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.AccountBalance>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountBalanceByAccount", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetAccountBalanceByAccount")
    @ResponseWrapper(localName = "getAccountBalanceByAccountResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetAccountBalanceByAccountResponse")
    public List<AccountBalance> getAccountBalanceByAccount(
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param messageId
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.Transaction>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransactionByProcessTransactionMessageId", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetTransactionByProcessTransactionMessageId")
    @ResponseWrapper(localName = "getTransactionByProcessTransactionMessageIdResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetTransactionByProcessTransactionMessageIdResponse")
    public List<Transaction> getTransactionByProcessTransactionMessageId(
        @WebParam(name = "messageId", targetNamespace = "")
        String messageId);

    /**
     * 
     * @param transactionUniPojo
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.Transaction>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransactionsByAllAttributes", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetTransactionsByAllAttributes")
    @ResponseWrapper(localName = "getTransactionsByAllAttributesResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetTransactionsByAllAttributesResponse")
    public List<Transaction> getTransactionsByAllAttributes(
        @WebParam(name = "transactionUniPojo", targetNamespace = "")
        TransactionUniversalPojo transactionUniPojo);

    /**
     * 
     * @param transactionRef
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.AccountBalance>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountBalanceByTxnRef", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetAccountBalanceByTxnRef")
    @ResponseWrapper(localName = "getAccountBalanceByTxnRefResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetAccountBalanceByTxnRefResponse")
    public List<AccountBalance> getAccountBalanceByTxnRef(
        @WebParam(name = "transactionRef", targetNamespace = "")
        String transactionRef);

    /**
     * 
     * @param openingDate
     * @param accountId
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.AccountBalance
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOpeningBalance", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetOpeningBalance")
    @ResponseWrapper(localName = "getOpeningBalanceResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetOpeningBalanceResponse")
    public AccountBalance getOpeningBalance(
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId,
        @WebParam(name = "openingDate", targetNamespace = "")
        XMLGregorianCalendar openingDate)
        throws Exception_Exception
    ;

    /**
     * 
     * @param closingDate
     * @param accountId
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.AccountBalance
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClosingBalance", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetClosingBalance")
    @ResponseWrapper(localName = "getClosingBalanceResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetClosingBalanceResponse")
    public AccountBalance getClosingBalance(
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId,
        @WebParam(name = "closingDate", targetNamespace = "")
        XMLGregorianCalendar closingDate)
        throws Exception_Exception
    ;

    /**
     * 
     * @param transactionRef
     * @param accountId
     * @return
     *     returns java.util.List<zw.co.esolutions.ewallet.bankservices.service.AccountBalance>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountBalanceByAccountIdAndTxnRef", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetAccountBalanceByAccountIdAndTxnRef")
    @ResponseWrapper(localName = "getAccountBalanceByAccountIdAndTxnRefResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetAccountBalanceByAccountIdAndTxnRefResponse")
    public List<AccountBalance> getAccountBalanceByAccountIdAndTxnRef(
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId,
        @WebParam(name = "transactionRef", targetNamespace = "")
        String transactionRef);

    /**
     * 
     * @param transactionPostingInfos
     * @param chargePostingInfos
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.EWalletPostingResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reverseEWalletEntries", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.ReverseEWalletEntries")
    @ResponseWrapper(localName = "reverseEWalletEntriesResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.ReverseEWalletEntriesResponse")
    public EWalletPostingResponse reverseEWalletEntries(
        @WebParam(name = "transactionPostingInfos", targetNamespace = "")
        List<TransactionPostingInfo> transactionPostingInfos,
        @WebParam(name = "chargePostingInfos", targetNamespace = "")
        List<ChargePostingInfo> chargePostingInfos)
        throws Exception_Exception
    ;

    /**
     * 
     * @param transactionPostingInfos
     * @param chargePostingInfos
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.EWalletPostingResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postEWalletEntries", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.PostEWalletEntries")
    @ResponseWrapper(localName = "postEWalletEntriesResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.PostEWalletEntriesResponse")
    public EWalletPostingResponse postEWalletEntries(
        @WebParam(name = "transactionPostingInfos", targetNamespace = "")
        List<TransactionPostingInfo> transactionPostingInfos,
        @WebParam(name = "chargePostingInfos", targetNamespace = "")
        List<ChargePostingInfo> chargePostingInfos)
        throws Exception_Exception
    ;

    /**
     * 
     * @param txnType
     * @param txnDate
     * @param accountId
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.TransactionSummaryItem
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransactionSummaryItem", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetTransactionSummaryItem")
    @ResponseWrapper(localName = "getTransactionSummaryItemResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetTransactionSummaryItemResponse")
    public TransactionSummaryItem getTransactionSummaryItem(
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId,
        @WebParam(name = "txnDate", targetNamespace = "")
        XMLGregorianCalendar txnDate,
        @WebParam(name = "txnType", targetNamespace = "")
        TransactionType txnType)
        throws Exception_Exception
    ;

    /**
     * 
     * @param txnDate
     * @param accountId
     * @return
     *     returns zw.co.esolutions.ewallet.bankservices.service.TransactionSummary
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransactionSummary", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetTransactionSummary")
    @ResponseWrapper(localName = "getTransactionSummaryResponse", targetNamespace = "http://service.bankservices.ewallet.esolutions.co.zw/", className = "zw.co.esolutions.ewallet.bankservices.service.GetTransactionSummaryResponse")
    public TransactionSummary getTransactionSummary(
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId,
        @WebParam(name = "txnDate", targetNamespace = "")
        XMLGregorianCalendar txnDate)
        throws Exception_Exception
    ;

}
