//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.referralservices.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ReferralService", targetNamespace = "http://service.referralservices.ewallet.esolutions.co.zw/", wsdlLocation = "http://localhost:9081/ReferralServices/ReferralService/ReferralService.wsdl")
public class ReferralService_Service
    extends Service
{

    private final static URL REFERRALSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9081/ReferralServices/ReferralService/ReferralService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        REFERRALSERVICE_WSDL_LOCATION = url;
    }

    public ReferralService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReferralService_Service() {
        super(REFERRALSERVICE_WSDL_LOCATION, new QName("http://service.referralservices.ewallet.esolutions.co.zw/", "ReferralService"));
    }

    /**
     * 
     * @return
     *     returns ReferralService
     */
    @WebEndpoint(name = "ReferralServiceSOAP")
    public ReferralService getReferralServiceSOAP() {
        return (ReferralService)super.getPort(new QName("http://service.referralservices.ewallet.esolutions.co.zw/", "ReferralServiceSOAP"), ReferralService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReferralService
     */
    @WebEndpoint(name = "ReferralServiceSOAP")
    public ReferralService getReferralServiceSOAP(WebServiceFeature... features) {
        return (ReferralService)super.getPort(new QName("http://service.referralservices.ewallet.esolutions.co.zw/", "ReferralServiceSOAP"), ReferralService.class, features);
    }

}
