CREATE TABLE BANKIF.Batch (id VARCHAR(30) NOT NULL, batchDate TIMESTAMP, complete SMALLINT, countValue BIGINT, dateCreated TIMESTAMP, entityId VARCHAR(30), maxValue INTEGER, nextBatchDate TIMESTAMP, ownerType VARCHAR(30), startIndex INTEGER, totalPoolAmount BIGINT, version INTEGER, PRIMARY KEY (id));

ALTER TABLE BANKIF.PROCESSTRANSACTION ADD AGENTNUMBER VARCHAR(10);