//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.bankservices.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "approveBankBranch", namespace = "http://service.bankservices.ewallet.esolutions.co.zw/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "approveBankBranch", namespace = "http://service.bankservices.ewallet.esolutions.co.zw/", propOrder = {
    "bankBranch",
    "userName"
})
public class ApproveBankBranch {

    @XmlElement(name = "bankBranch", namespace = "")
    private zw.co.esolutions.ewallet.bankservices.model.BankBranch bankBranch;
    @XmlElement(name = "userName", namespace = "")
    private String userName;

    /**
     * 
     * @return
     *     returns BankBranch
     */
    public zw.co.esolutions.ewallet.bankservices.model.BankBranch getBankBranch() {
        return this.bankBranch;
    }

    /**
     * 
     * @param bankBranch
     *     the value for the bankBranch property
     */
    public void setBankBranch(zw.co.esolutions.ewallet.bankservices.model.BankBranch bankBranch) {
        this.bankBranch = bankBranch;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * 
     * @param userName
     *     the value for the userName property
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

}
