//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.bankservices.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "getBankAccountByLevelAndStatus", namespace = "http://service.bankservices.ewallet.esolutions.co.zw/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getBankAccountByLevelAndStatus", namespace = "http://service.bankservices.ewallet.esolutions.co.zw/", propOrder = {
    "arg0",
    "arg1"
})
public class GetBankAccountByLevelAndStatus {

    @XmlElement(name = "arg0", namespace = "")
    private zw.co.esolutions.ewallet.enums.BankAccountLevel arg0;
    @XmlElement(name = "arg1", namespace = "")
    private zw.co.esolutions.ewallet.enums.BankAccountStatus arg1;

    /**
     * 
     * @return
     *     returns BankAccountLevel
     */
    public zw.co.esolutions.ewallet.enums.BankAccountLevel getArg0() {
        return this.arg0;
    }

    /**
     * 
     * @param arg0
     *     the value for the arg0 property
     */
    public void setArg0(zw.co.esolutions.ewallet.enums.BankAccountLevel arg0) {
        this.arg0 = arg0;
    }

    /**
     * 
     * @return
     *     returns BankAccountStatus
     */
    public zw.co.esolutions.ewallet.enums.BankAccountStatus getArg1() {
        return this.arg1;
    }

    /**
     * 
     * @param arg1
     *     the value for the arg1 property
     */
    public void setArg1(zw.co.esolutions.ewallet.enums.BankAccountStatus arg1) {
        this.arg1 = arg1;
    }

}
