//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.bankservices.service.jaxws;

import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "getOpeningBalance", namespace = "http://service.bankservices.ewallet.esolutions.co.zw/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOpeningBalance", namespace = "http://service.bankservices.ewallet.esolutions.co.zw/", propOrder = {
    "accountId",
    "openingDate"
})
public class GetOpeningBalance {

    @XmlElement(name = "accountId", namespace = "")
    private String accountId;
    @XmlElement(name = "openingDate", namespace = "")
    private Date openingDate;

    /**
     * 
     * @return
     *     returns String
     */
    public String getAccountId() {
        return this.accountId;
    }

    /**
     * 
     * @param accountId
     *     the value for the accountId property
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * 
     * @return
     *     returns Date
     */
    public Date getOpeningDate() {
        return this.openingDate;
    }

    /**
     * 
     * @param openingDate
     *     the value for the openingDate property
     */
    public void setOpeningDate(Date openingDate) {
        this.openingDate = openingDate;
    }

}
