/**
 * 
 */
package zw.co.esolutions.merchants.util;

/**
 * @author blessing
 *
 */
public interface InterfaceConstants {

	String STATUS_REVERSAL_REQUEST = "REVERSAL RQST";
	String STATUS_REVERSAL_FAILED = "REVERSAL FAILED";
	String STATUS_REVERSAL_SUCCESSFUL = "REVERSAL SUCCESSFUL";
	String STATUS_CREDIT_REQUEST = "CREDIT RQST";
	String STATUS_SUCCESSFUL = "SUCCESSFUL";
	String STATUS_FAILED = "FAILED";
	String STATUS_VALIDATION_REQUEST = "VALIDATION RQST";
	
	String RC_OK = "00";
	String BALANCE_SIGN_D = "D";
	String BALANCE_SIGN_C = "C";
	
	String TXN_TYPE_ACCOUNT_VALIDATION = "ACCOUNT VALIDATION";
	String TXN_TYPE_CREDIT = "CREDIT RQUEST";
	String TXN_TYPE_REVERSAL = "REVERSAL REQUEST";
	
	String PCODE30 = "300000";
	String PCODEU5 = "U50000";
	
	int ISO_FIELD_PRIMARY_ACCOUNT_NUMBER = 2;

	int ISO_FIELD_PROCESSING_CODE = 3;

	int ISO_FIELD_TRANSACTION_AMOUNT = 4;

	int ISO_FIELD_TRANSMISSION_DATE = 7;

	int ISO_FIELD_SYSTEMS_TRACE_AUDIT = 11;

	int ISO_FIELD_MERCHANT_TYPE = 18;

	int ISO_FIELD_ACQUIRING_INSTITUTION_ID = 32;

	int ISO_FIELD_FORWARDING_INSTITUTION_ID = 33;
	
	int ISO_FIELD_PRIMARY_ACCOUNT_EXTENDED = 34;

	int ISO_FIELD_RETRIEVAL_REF = 37;

	int ISO_FIELD_AUTHORIZATION_ID_RESPONSE = 38;

	int ISO_FIELD_RESPONSE_CODE = 39;

	int ISO_FIELD_CARD_ACCEPTOR_TERMINAL_ID = 41;
	
	int ISO_FIELD_CARD_ACCEPTOR_ID = 42;

	int ISO_FIELD_CARD_ACCEPTOR_NAME_LOCATION = 43;

	int ISO_FIELD_ADDITIONAL_RESPONSE_DATA = 44;

	int ISO_FIELD_ADDITIONAL_DATA_ISO = 46;

	int ISO_FIELD_TRANSACTION_CURRENCY_CODE = 49;

	int ISO_FIELD_ADDITIONAL_AMOUNTS = 54;

	int ISO_FIELD_OTHER_AMOUNT = 61;

	int ISO_FIELD_ORIGINAL_DATA_ELEMENTS = 90;

	int ISO_FIELD_REPLACEMENT_AMOUNTS = 95;

	/** Source Account or From Account. */
	int ISO_FIELD_ACCOUNT_IDENTIFICATION_1 = 102;

	/** Target Account or To Account. */
	int ISO_FIELD_ACCOUNT_IDENTIFICATION_2 = 103;

	/** Utility Account */
	int ISO_FIELD_TRANSACTION_DESCRIPTION = 104;
	
	String MTI_TXN_RQST = "0200";
	String MTI_TXN_RESP = "0210";
	String MTI_REVERSAL_RQST = "0420";
	String MTI_REVERSAL_RESP = "0430";
	
	
	
	
}
