//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.process.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "checkIfAnyFloatsPendingApproval", namespace = "http://process.ewallet.esolutions.co.zw/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "checkIfAnyFloatsPendingApproval", namespace = "http://process.ewallet.esolutions.co.zw/")
public class CheckIfAnyFloatsPendingApproval {

    @XmlElement(name = "profileId", namespace = "")
    private String profileId;

    /**
     * 
     * @return
     *     returns String
     */
    public String getProfileId() {
        return this.profileId;
    }

    /**
     * 
     * @param profileId
     *     the value for the profileId property
     */
    public void setProfileId(String profileId) {
        this.profileId = profileId;
    }

}
