//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.process.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "editDayEndSummary", namespace = "http://process.ewallet.esolutions.co.zw/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "editDayEndSummary", namespace = "http://process.ewallet.esolutions.co.zw/", propOrder = {
    "summary",
    "userName"
})
public class EditDayEndSummary {

    @XmlElement(name = "summary", namespace = "")
    private zw.co.esolutions.ewallet.process.model.DayEndSummary summary;
    @XmlElement(name = "userName", namespace = "")
    private String userName;

    /**
     * 
     * @return
     *     returns DayEndSummary
     */
    public zw.co.esolutions.ewallet.process.model.DayEndSummary getSummary() {
        return this.summary;
    }

    /**
     * 
     * @param summary
     *     the value for the summary property
     */
    public void setSummary(zw.co.esolutions.ewallet.process.model.DayEndSummary summary) {
        this.summary = summary;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * 
     * @param userName
     *     the value for the userName property
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

}
