//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.process.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "getProcessTransaction", namespace = "http://process.ewallet.esolutions.co.zw/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProcessTransaction", namespace = "http://process.ewallet.esolutions.co.zw/")
public class GetProcessTransaction {

    @XmlElement(name = "info", namespace = "")
    private zw.co.esolutions.ewallet.process.util.NonHolderWithdrawalInfo info;

    /**
     * 
     * @return
     *     returns NonHolderWithdrawalInfo
     */
    public zw.co.esolutions.ewallet.process.util.NonHolderWithdrawalInfo getInfo() {
        return this.info;
    }

    /**
     * 
     * @param info
     *     the value for the info property
     */
    public void setInfo(zw.co.esolutions.ewallet.process.util.NonHolderWithdrawalInfo info) {
        this.info = info;
    }

}
