//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.process.jaxws;

import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "getTellerNetCashPosition", namespace = "http://process.ewallet.esolutions.co.zw/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTellerNetCashPosition", namespace = "http://process.ewallet.esolutions.co.zw/", propOrder = {
    "profileId",
    "date"
})
public class GetTellerNetCashPosition {

    @XmlElement(name = "profileId", namespace = "")
    private String profileId;
    @XmlElement(name = "date", namespace = "")
    private Date date;

    /**
     * 
     * @return
     *     returns String
     */
    public String getProfileId() {
        return this.profileId;
    }

    /**
     * 
     * @param profileId
     *     the value for the profileId property
     */
    public void setProfileId(String profileId) {
        this.profileId = profileId;
    }

    /**
     * 
     * @return
     *     returns Date
     */
    public Date getDate() {
        return this.date;
    }

    /**
     * 
     * @param date
     *     the value for the date property
     */
    public void setDate(Date date) {
        this.date = date;
    }

}
