//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package zw.co.esolutions.ewallet.process.jaxws;

import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "scheduleTimer", namespace = "http://process.ewallet.esolutions.co.zw/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "scheduleTimer", namespace = "http://process.ewallet.esolutions.co.zw/", propOrder = {
    "dayOfMonth",
    "hour",
    "minutes",
    "isForThisMonth",
    "runDate"
})
public class ScheduleTimer {

    @XmlElement(name = "dayOfMonth", namespace = "")
    private String dayOfMonth;
    @XmlElement(name = "hour", namespace = "")
    private String hour;
    @XmlElement(name = "minutes", namespace = "")
    private String minutes;
    @XmlElement(name = "isForThisMonth", namespace = "")
    private boolean isForThisMonth;
    @XmlElement(name = "runDate", namespace = "")
    private Date runDate;

    /**
     * 
     * @return
     *     returns String
     */
    public String getDayOfMonth() {
        return this.dayOfMonth;
    }

    /**
     * 
     * @param dayOfMonth
     *     the value for the dayOfMonth property
     */
    public void setDayOfMonth(String dayOfMonth) {
        this.dayOfMonth = dayOfMonth;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getHour() {
        return this.hour;
    }

    /**
     * 
     * @param hour
     *     the value for the hour property
     */
    public void setHour(String hour) {
        this.hour = hour;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getMinutes() {
        return this.minutes;
    }

    /**
     * 
     * @param minutes
     *     the value for the minutes property
     */
    public void setMinutes(String minutes) {
        this.minutes = minutes;
    }

    /**
     * 
     * @return
     *     returns boolean
     */
    public boolean getIsForThisMonth() {
        return this.isForThisMonth;
    }

    /**
     * 
     * @param isForThisMonth
     *     the value for the isForThisMonth property
     */
    public void setIsForThisMonth(boolean isForThisMonth) {
        this.isForThisMonth = isForThisMonth;
    }

    /**
     * 
     * @return
     *     returns Date
     */
    public Date getRunDate() {
        return this.runDate;
    }

    /**
     * 
     * @param runDate
     *     the value for the runDate property
     */
    public void setRunDate(Date runDate) {
        this.runDate = runDate;
    }

}
