//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-05/12/2011 11:54 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.13 at 02:21:41 PM CAT 
//


package zw.co.esolutions.mcommerce.xml;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import zw.co.esolutions.merchants.beans.TransactionState;




/**
 * <p>Java class for ISOMsg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ISOMsg">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="field" type="{http://xml.mcommerce.esolutions.co.zw}ISOMsgField" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="mti" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="retrievalReference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ISOMsg", propOrder = {
    "field"
})
@Entity
@Table(name = "MerchantRequest")
public class ISOMsg {

	@XmlTransient
	@Id
	@Column(length = 40)
	private String txnRef; 
	
	@XmlElement(required = true)
	@ElementCollection
	@CollectionTable(name = "ISOMsgField", joinColumns = @JoinColumn(name = "txnRef", referencedColumnName = "txnRef"))
	protected List<ISOMsgField>	field;

	@XmlTransient
	@OneToMany(mappedBy = "isoMsg")
	private List<TransactionState> transactionStates;
	
	@XmlTransient
	private MetaData metaData;
	
	@XmlAttribute
	@Column(length = 8)
	protected String mti;

	@XmlAttribute
	@Column(length = 25)
	protected String retrievalReference;
	
	@XmlTransient
	@Column(length = 20)
	private String status;
	
	@XmlTransient
	@Column(length = 20)
	private String txnType;

	@XmlTransient
	@Column(length = 300)
	private String narrative;

	@XmlTransient
	@Version
	private long version;

	
    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ISOMsgField }
     * 
     * 
     */
	   public List<ISOMsgField> getField() {
	        if (field == null) {
	            field = new ArrayList<ISOMsgField>();
	        }
	        return this.field;
	    }
	    
		public ISOMsgField getISOField(int number) {
			for (ISOMsgField f : getField()) {
				if (f.getNumber() == number)
					return f;
			}
			return new ISOMsgField(number,"");
		}
		
		public String getFieldValue(int fieldNumber){
			return this.getISOField(fieldNumber).getValue();
		}
		
		public ISOMsgField getISOFieldFromList(int number) {
			for (ISOMsgField f : getField()) {
				if (f.getNumber() == number)
					return f;
			}
			return null;
		}

		public void setISOField(int number, String value) {
			ISOMsgField f = getISOFieldFromList(number);
			if (f == null)
				getField().add(new ISOMsgField(number, value));
			else {
				f.setValue(value);
			}
		}

    /**
     * Gets the value of the mti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMti() {
        return mti;
    }

    /**
     * Sets the value of the mti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMti(String value) {
        this.mti = value;
    }

    /**
     * Gets the value of the retrievalReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetrievalReference() {
        return retrievalReference;
    }

    /**
     * Sets the value of the retrievalReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetrievalReference(String value) {
        this.retrievalReference = value;
    }

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getNarrative() {
		return narrative;
	}

	public void setNarrative(String narrative) {
		this.narrative = narrative;
	}

	public long getVersion() {
		return version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	public String getTxnType() {
		return txnType;
	}

	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}

	public List<TransactionState> getTransactionStates() {
		return transactionStates;
	}

	public void setTransactionStates(List<TransactionState> transactionStates) {
		this.transactionStates = transactionStates;
	}

	public MetaData getMetaData() {
		return metaData;
	}

	public void setMetaData(MetaData metaData) {
		this.metaData = metaData;
	}

	public String getTxnRef() {
		return txnRef;
	}

	public void setTxnRef(String txnRef) {
		this.txnRef = txnRef;
	}

}
