//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-05/12/2011 11:54 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.13 at 02:21:41 PM CAT 
//


package zw.co.esolutions.mcommerce.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="metadata" type="{http://xml.mcommerce.esolutions.co.zw}MetaData" minOccurs="0"/>
 *         &lt;element name="isoMsg" type="{http://xml.mcommerce.esolutions.co.zw}ISOMsg"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadata",
    "isoMsg"
})
@XmlRootElement(name = "messages")
public class Messages {

    protected MetaData metadata;
    @XmlElement(required = true)
    protected ISOMsg isoMsg;

//    @XmlTransient
//    private boolean reversal;
//    
//    @XmlTransient
//    private boolean validation;
//    
//    @XmlTransient
//    private boolean submitToMerchant;
//    
//    @XmlTransient
//    private boolean submitReply;
    
    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link MetaData }
     *     
     */
    public MetaData getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaData }
     *     
     */
    public void setMetadata(MetaData value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the isoMsg property.
     * 
     * @return
     *     possible object is
     *     {@link ISOMsg }
     *     
     */
    public ISOMsg getIsoMsg() {
        return isoMsg;
    }

    /**
     * Sets the value of the isoMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISOMsg }
     *     
     */
    public void setIsoMsg(ISOMsg value) {
        this.isoMsg = value;
    }

//	public boolean isReversal() {
//		return reversal;
//	}
//
//	public void setReversal(boolean reversal) {
//		this.reversal = reversal;
//	}
//
//	public boolean isValidation() {
//		return validation;
//	}
//
//	public void setValidation(boolean validation) {
//		this.validation = validation;
//	}
//
//	public boolean isSubmitToMerchant() {
//		return submitToMerchant;
//	}
//
//	public void setSubmitToMerchant(boolean submitToMerchant) {
//		this.submitToMerchant = submitToMerchant;
//	}
//
//	public boolean isSubmitReply() {
//		return submitReply;
//	}
//
//	public void setSubmitReply(boolean submitReply) {
//		this.submitReply = submitReply;
//	}

}
